### ISSUE TITLE
Vytal

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#118]
anything exciting in [here](https://github.com/z0ccc/Vytal) that can enhance prototype/proxy lies

**Comment by abrahamjuliot** [comment]
I'm reviewing. Looks cool. There a lot of unique methods here too. The essential prototype tests are implemented there, but nothing new. I provided some guidance a while back to the dev at `creepjs/discussions/149`.

https://github.com/z0ccc/Vytal/blob/48ba11d6a1e14ebd452f2dffe1b747b536dbd63d/frontend/src/utils/navigator.js#L214-L244

**Comment by Thorin-Oakenpants** [comment]
Yeah, I also gave him pointers on detecting TB client side :)

**Comment by Thorin-Oakenpants** [comment]
in terms of grabbing metrics, nothing for me to do here .. in terms of lies, creepy is on it .. closing
