### ISSUE TITLE
ToDo: sectionized hashes

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#12]
It's a bit of a loaded issue, and I'm not 100% sure of the plan. I may need to have two or more sets (but only one for display)

* [ ] maybe add an info/readme/about section which outlines what the hashes mean
   - use an overlay that you can pop up so it doesn't pollute the page
   - i.e hashes are only calculated when `run/re-run` - no real time updating
   - that they are selective - e.g. changing your window size won't change anything (also see real time updating since some screen metrics are real time)
   - hashes do not include any manual tests `click here`
   - expand it to say tzp is only designed for current ESR/FF/TB
   - expand it to say no PII is keep and persistent/session storage is only used once per run
   - just keep it super short and sweet, although if collapsed by default this is not an deciding issue
   
- 🔸 the purpose(s)
   - the data quality: some of which can be handled at the backend
   - output a total hash maybe (I find these highly misleading to laypeople)
   - the displayed hashes should be as stable as possible (zoom resistant, spoof resistant  etc - where possible)
   - maybe I need a shadow data set
- 🔸 item 1: manual tests
   - anything with `click here` is not part of the section hash, but we might want to collect some of those as well
   - I plan on fixing up the audio section: so each section only has one `re-run`/`run`
- 🔸 item 2: auto send  or submit button
   - submit would make it easy to include manual data (at this point I'm think of the manual audio and maybe tests that require user permission: such as allowing camera/devices etc)
   - or auto submit each `click here` independently ? yikes
- 🔸 item 3: nested data arrays
   - some of the data line items are just a hash and we **may** need to dig deeper (i.e send back the results)
   - example widgets: is it the sizes or the widget font?
   - example fonts: a hash doesn't help with working out what fonts are outliers in results
   - there may be some equivalency, but having hard data to drill into helps
- 🔸 item 4: BS and lies
   - not an issue, just something to aware of, although the level/type of BS can provide entropy
   - note: we can detect isFF (and isTB as an extra flag), so we would only collect gecko results
   - e.g: noise detection in domrect and canvas
   - e.g: UA which is not important
     - we can already get OS + version and we KNOW the formula Mozilla uses
     - RFP already has this covered, it's not something we need to actually collect, but we do need to section hash it
     - as long as someone isn't lying (and RFP is off) then the extra such as OS architecture can help in analysis: we just need to weed out the BS that would taint results
- 🔸 item 5: data quality vs stability
   - the section hash can
     - modifying what is hashed vs what is displayed as items
     - by excluding items (some are redundant)
     - loss of data or data precision needs to be weight up
     - I guess I just need to decide on each metric on it's own as to how important is it
- 🔹 item 5: examples
   - e.g. feature detection doesn't collect the actual scrollbar width: it only collects a boolean of is it higher than zero or not: since macOS has a feature to turn an overlay scrollbar on/off. scrollbar widths change with zoom
   - e.g. css line height is another
   - e.g. in screen metrics I don't plan on collecting actual window/screen measurements, just a set of booleans

here's a peek, lots to do, finish
![lots-to-do](https://user-images.githubusercontent.com/16656956/94770818-16169d00-03a5-11eb-8251-77daeb6ee2b5.png)

**Comment by Thorin-Oakenpants** [comment]
With a global rerun button (which I added to better gauge perf), this actually is cool for holding multiple levels of fingerprints and makes its easy to spot if it changes when you zoom or something. I can also use this section to output each FP's contents - which is a step closer to being able to compare them

I can prefix all metrics with an extra delimited (delimiter is `:`) number: e.g.
- `3: errors: hash-values`
- `2: inner window: 1000x900`

And I can decide that level before I resolve it: e.g. hardware concurrency on Brave (if I cared about them) could be loose, but on Firefox be stable: Not to be confused with detecting randomness or noise or lies within a metric and returning that as the stable result

So every metric is auto added to the everything FP which has no number: this is the data sent to the backend. Then I create FP arrays 1,2,4,8,16,32. What I pass on each metric is what it gets added to: so 63 means all of those, but 25 means 16+8+1. So in the above example FP1 array is the stable one, FP2 array is the loose one. So the error hash goes in both, but the inner window only goes in the loose one. Capisce?

So yeah, now TZP could be used to find stability, which isn't it's real purpose: and could always be done on the backend. This also solves the issue of how to collect "everything" for the backend dataset (e.g currently I don't collect the stack depth)

User initiated/extra items are all done with `click here` buttons, and they are never part of the section hash. Not sure I need to say that anywhere

So it just remains for me promisify returns including iframes and workers (and add those iframes/workers where needed like devices, headers etc). I don't need a ticket open to do this.

That was my story, thanks for listening :)

**Comment by Thorin-Oakenpants** [comment]
@abraham: whats an elegant function to determine the bitfields (is that the right term)?
 eg 25 return [16,8,1]

**Comment by abrahamjuliot** [comment]
[Bitfields](https://emergent.systems/blog/bit-fields/) is an interesting subject. That might be unrelated.

I'm not sure if this is what you are looking for, but you can use a hashmap or hashtable.
```js
hashMap = new Map([
 [25, [16,8,1]],
 [63, [32,16,8,4,2,1]],
 // etc...
])
hashMap.has(25) // true
hashMap.get(25) // [16, 8, 1]

hashTable = {
  25: [16,8,1],
  63: [32,16,8,4,2,1]
  // etc...
}
!!hashTable[25] // true
hashTable[25] // [16, 8, 1]
```

**Comment by Thorin-Oakenpants** [comment]
ahh .. not what I was thinking... it should be simple enough to calculate on the fly as a mathematical answer (i.e I wouldn't need 64, or 128, or 256 map entries)

but... there's a bit of a flaw in this: if I'm passing a number from each section function, spread over numerous js files, then when I want to create a new one, I have to go do a bunch of edits all over the place: and numbers aren't very friendly

So, after your insight, I think its better centralized: eg metric-name + arrays-names: e.g

```js
const hashMap = new Map([
 ["screen-inner", ["loose"]],
 ["ua-errors", ["stable", "loose"]],
 ["ua-widgets", ["stable", "loose"]],
])
```

that way I have a master array + reference of what goes where, and can easily add new FP sets and play with them from one place .. excellent thinking
