### ISSUE TITLE
window keys: creep vs tzp

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#132]
@abrahamjuliot 

something I noticed
- FF nightly: tzp-839 properties vs c-837
- opera: tzp-997 vs c-997
- chrome: tzp-1004 vs creep-1004

so it's a gecko thing (I thought it might be because the console is open, but alas that is not it). I tested older FFs
- FF60:  tzp-769 (creep broken by webrtc)
- FF68 tzp-784 c-782 - same two items difference
- I stopped there

the gecko difference is always `Performance` and `PerformanceNavigationTiming`

I hate it when code doesn't replicate - who knows what else you could drop off (that adds entropy) or me pick up (that are not stable). I though we were the same. Why the difference?

Please explain yourself young man :)

**Comment by abrahamjuliot** [comment]
😁
Yes, `Performance` and `PerformanceNavigationTiming` are removed and the `Event` is moved to the end of the list.

As far as I know, this adds a bit of stability when the console is opened/closed or RFP is turned on/off, but I'm not sure if it adds much. On creep, this reduces the amount of unique window samples captured and lowers the count of loose fingerprint switching tracked. I have not tested this in older versions yet. 

```js
// if Firefox, remove the 'Event' key and push to end for consistent order
// and disregard keys known to be missing in RFP mode
if (isFirefox) {
    const keyMovedByInspect = 'Event'
    const keysMissingInRFP = ['PerformanceNavigationTiming', 'Performance']
    const index = keys.indexOf(keyMovedByInspect)
    if (index != -1) {
        keys = keys.slice(0, index).concat(keys.slice(index + 1))
        keys = [...keys, keyMovedByInspect]
    }
    keysMissingInRFP.forEach(key => {
        const index = keys.indexOf(key)
        if (index != -1) {
            keys = keys.slice(0, index).concat(keys.slice(index + 1))
        }
        return keys
    })
}
```

**Comment by Thorin-Oakenpants** [comment]
Ahh, BTW, I sort gecko results but not others - that takes care of the console being open for me (IDK about chrome, I thought that was covered)

`Performance` is not missing with RFP on (at least not in nightly) - no big deal, it was probably missing in earlier versions - probably changed when they tweaked performance entries - probably this one - https://bugzilla.mozilla.org/show_bug.cgi?id=1637985

Entropy wise, I'm happy to collect those two values, I mean it's entropy :)

**Comment by Thorin-Oakenpants** [comment]
actually, I do sort them for all engines - I just do some gecko stuff before sorting

I played with my code and did some debugging
```
ESR78 // bca850600dfb

RFP off 813

console open
last 4 items: Node,Document,HTMLDocument,Performance
last 4 items: Document,HTMLDocument,Performance,Event <-- storage tab selected at some stage - becomes sticky
RFP items: Performance,PerformanceNavigationTiming
sorted hash: eb06d1c4372efeef24c472f28b152f19323ced86


console closed
last 4 items: netscape,Node,Document,HTMLDocument
RFP items: Performance,PerformanceNavigationTiming
sorted hash: eb06d1c4372efeef24c472f28b152f19323ced86

--------

RFP on 812

console open
last 4 items: Node,Document,HTMLDocument,Performance
last 4 items: Document,HTMLDocument,Performance,Event <-- all you have to do is select/deselect storage tab
RFP items: Performance
sorted hash: c82a70670ecc84e9a55e4ffe34e190e74ecd7024

console closed
last 4 items: netscape,Node,Document,HTMLDocument
RFP items: Performance
sorted hash: c82a70670ecc84e9a55e4ffe34e190e74ecd7024
```

So yeah, I remember this, might have been in the old TZP repo .. where sorting created stability. That storage tab must fire an event or something - so in FF the last items are always predicable, which is how I spot the fake shit

```js
if (isFF && !isFFLegacy) {
	// suspect
	suspectProps = props.slice(props.indexOf("Performance")+1)
	let falsePos = ['Event','StyleSheetList'] // false positives
	suspectProps = suspectProps.filter(x => !falsePos.includes(x))
	if (suspectProps.length) {
		sDetail[sSuspect] = suspectProps.sort()
		// fake
		fakeProps = suspectProps.filter(x => !knownGood.includes(x))
		if (fakeProps.length) {
			props = props.filter(x => !fakeProps.includes(x))
			sDetail[sFake] = fakeProps.sort()
			// do stuff with fake
		}
	}
}
```

but now I'm confused (again) .. I'm slicing at `Performance` + 1, but how does that work when the last item is `HTMLDocument` - reopening to remind myself to check this

I'll check the other FF versions to see where RFP dropped `Performance`

**Comment by Thorin-Oakenpants** [comment]
OK, so I fixed my debug code

```
95 RFP off
closed
	- last 4 items: HTMLDocument,EventCounts,Map,Performance
	- RFP items: Performance (838/838),PerformanceNavigationTiming (338/838)
open
	- last 4 items: EventCounts,Map,Performance,Event
	- RFP items: Performance (837/838),PerformanceNavigationTiming (337/838)
open - select storage
	- last 4 items: Map,Performance,Event,Location
	- RFP items: Performance (836/838),PerformanceNavigationTiming (336/838)

95 RFP on
closed
	- last 4 items: HTMLDocument,EventCounts,Map,Performance
	- RFP items: Performance (837/837)
open
	- last 4 items: EventCounts,Map,Performance,Event
	- RFP items: Performance (836/837)
open - select storage
	- last 4 items: Map,Performance,Event,Location
	- RFP items: Performance (835/837)

```

check - RFP drops `PerformanceNavigationTiming`

in gecko, `Performance` is always last. But if the console is open, the last item is `Event`. But if you select the Storage tab, even if you select then deselect it, it seems as if in FF95 at least, the last item now becomes `Location` (I didn't have that in my false positives, only in knownGood - I will patch that)

And I also have `StyleSheetList` as a false positive as well (I think its FF < 62 or something). So in gecko, I find Performance, ignore `Event` `Location` and `StyleSheetList` and anything after that is suspect (things extensions are playing with) and from the suspect list I remove knownGood = lets me catch the fake random items from chameleon, and the fake items from cydec

So I had it right - as long as Performance is always expected regardless of RFP. Now imma gonna test, thanks a bunch - to see if/when RFP affected `Performance` (it didn't in ESR78) and I rely on this, so it better not :)

**Comment by Thorin-Oakenpants** [comment]
OK, I'll finish testing later, but here we go
 - am up to FF65 (but it FF62+ matches FF nightly)
 - I don't think android would have been any different
 - the second set for `console-y` is when you have selected the storage tab at some stage

AFAICT,  RFP doesn't affect Performance (so far) being at the end (or very near end)

```
note: TZP code ignores isFFLegacy (< v60) and doesn't attempt to find fake/suspect
e.g. FF52 ended in a whole heap of `CSS*` stuff

FF60-61
- RFP-n console-n: Node,Document,HTMLDocument,Performance
- RFP-y console-n: Node,Document,HTMLDocument,Performance
- RFP-n console-y: HTMLDocument,Performance,Event,StyleSheetList / Performance,Event,StyleSheetList,Location
- RFP-y console-y: HTMLDocument,Performance,Event,StyleSheetList / Performance,Event,StyleSheetList,Location

FF62+
- RFP-n console-n: Node,Document,HTMLDocument,Performance
- RFP-y console-n: Node,Document,HTMLDocument,Performance
- RFP-n console-y: Document,HTMLDocument,Performance,Event / HTMLDocument,Performance,Event,Location
- RFP-y console-y: Document,HTMLDocument,Performance,Event / HTMLDocument,Performance,Event,Location
```

**Comment by Thorin-Oakenpants** [comment]
I think I screwed up my earlier tests (since edited)

see this
https://github.com/arkenfox/TZP/blob/88df9aaaa38e99f058fbee6c6e667be90a3aa0b7/js/misc.js#L75

and now see this - https://github.com/arkenfox/TZP/commit/88df9aaaa38e99f058fbee6c6e667be90a3aa0b7

i used to `let allProps = props` and even though it's an array, sorting either also sorts the other, but now I do this
- `props.forEach(function(item) {allProps.push(item)})` and they're not entangled

I thought only objects had that fucked up quantum entanglement

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/TZP/blob/88df9aaaa38e99f058fbee6c6e667be90a3aa0b7/js/misc.js#L86

OK, tested 37 browsers, six tests each, new tab when switching to RFP on
- `Performance` is always last (or almost last if console open)
  - RFP doesn't affect this
- If console is open
- FF60-61: `Event + StyleSheetList` or `Event + StyleSheetList + Location` comes after Performance
- FF62+ `Event` or `Event + Location` comes after Performance

```
FF60-61
- RFP-any console-n: Node,Document,HTMLDocument,Performance
- RFP-any console-y: HTMLDocument,Performance,Event,StyleSheetList / Performance,Event,StyleSheetList,Location

FF62-88
- RFP-any console-n: Node,Document,HTMLDocument,Performance
- RFP-any console-y: Document,HTMLDocument,Performance,Event / HTMLDocument,Performance,Event,Location

FF89-96
- RFP-any console-n: HTMLDocument,EventCounts,Map,Performance
- RFP-any console-y: EventCounts,Map,Performance,Event / Map,Performance,Event,Location
```

my work here is done

**Comment by Thorin-Oakenpants** [comment]
PS: all the extra shit in TB is from NoScript - I tested them as well with and without NoScript extension enabled (ESR60, 68, 78, 91)
- I don't treat these as false positives, but as suspect (but knownGood)

https://github.com/arkenfox/TZP/blob/32ebe3e7e41d930fc480ff7a2d000d82805e121d/js/misc.js#L36-L39

...aaaaaaand .. now my work is done

**Comment by Thorin-Oakenpants** [comment]
noted for posterity
```js
	// https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41694
		// allowlist NS 11.4.20+ - i.e remove false positives
		// allow slider at safer
	aFilter = ["Element","Event","HTMLCanvasElement","HTMLElement","HTMLFrameElement",
		"HTMLIFrameElement","HTMLObjectElement","Location","MediaSource","Proxy","URL","webkitURL"
	]
```

event and location are there because they can come after performance depending on the console being open and if various tabs have been used (I think it was storage or network adds Location) - so the five in the linked tor ticket are standard, the rest are added when on safer - FYI, time for some 💤

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot btw your windows properties hash changes if the console is open or closed in FF

e.g. nightly
```
Window 908c6d8a keys (926): console closed
Window 0feadc66 keys (926): console open and sitting on console, not touched any other tabs
Window 501bc8b6 keys (926): console open and I have visited the storage tab
``

look at https://github.com/arkenfox/TZP/blob/0a40c27b57f2194bf5d5eb1a585e085fac6991f2/js/misc.js#L767-L775

mine is solid and stable as F and I don't remove any properties like you do :~

**Comment by abrahamjuliot** [comment]
Nice. I need to use sorting before hashing. Another option is to hardcode all the long-standing items and then mark what is added or removed.

**Comment by Thorin-Oakenpants** [comment]
nah, you don't sort, you just move the problematic ones, if they are present, to the end in the same order, then you hash :)

you jelly?

**Comment by abrahamjuliot** [comment]
I am bit jelly 😅
