### ISSUE TITLE
canvas stuff

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#14]
maybe I'm confused

I'm cleaning up (and finishing) various tests for the index (loads more to come).. in the [canvas spoof fingerprinting](https://arkenfox.github.io/TZP/tests/canvasnoise.html) I'm not sure if I'm doing something wrong

with RFP on - here's an example
![test](https://user-images.githubusercontent.com/16656956/95053215-a293c900-06df-11eb-86ec-dc9427f9f1d9.png)

the first array is what I `set` array, the second is what I `read` back
the other line at the top is the first cell (0,0) and is the value I'm writing to the `what we read back` canvas, so users can visually see that it changed (of course subtle changes will be hard to see)

here's an enlargement
![enlarged](https://user-images.githubusercontent.com/16656956/95053520-12a24f00-06e0-11eb-8c8d-aa10bc03e91b.png)

But I'm so confused, because I thought RFP caused patterns like those in the PNGs (toDataURL, toBlob) - so now I'm questioning if I did this correctly (i.e displaying what we read back)

For example if you go to these
- [CB tests](https://canvasblocker.kkapsner.de/test/test.html) you see those RFP patterns (but it's displaying toDataURL)
- [browserleaks](https://browserleaks.com/canvas) - that too only shows an image

So I guess because of all those tests (and questions on reddit and on arkenfox user.js), I ended up thinking all methods display as that RFP pattern - but what I'm showing is the real thing (not an image). I wonder why images get a pattern?

@kkapsner @abrahamjuliot : am I doing it right? Where I read the values back from the ctrl (the small visual where it says `what we set`), I write that same value to the `getImageData` (the one where is says `what we read back`)

https://github.com/arkenfox/TZP/blob/776b16160a44f2715abdd081f9775f82f2ba8a27/tests/canvasnoise.html#L137-L154

I think I'll add a second large visual

**Comment by Thorin-Oakenpants** [comment]
OK, after adding a second large visual, I answered my own question: yup, it's working as intended (right? why do I keep second guessing myself? .. is is correct, right guys?)

**Comment by kkapsner** [comment]
So you're saying that you get the real values if you use getImageData if RFP is enabled? That means that RFP is not protecting getImageData...
I added a getImageData test to my [test page](https://canvasblocker.kkapsner.de/test/test.html) and RFP seems to work fine. Which FF version were you testing?

**Comment by Thorin-Oakenpants** [comment]
Nope. RFP works perfectly. I was wondering why getImageData is random whereas the PNGs have a pattern - and this made me question myself

your test shows e.g.
```html
<h3>getimageData Test</h3>
<canvas class="display" height="30" width="220" title="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANwAAAAeCAYAAABHenA+AAAAwklEQVR4nO3VoQ3CUABF0e9qCTNUMARgCJguUEMdiimQWCwOwQw4EjRr4EnQJCxB2uT16GOuu6W9dOfV8vN9zd7X+WK9q/eP0+HZVNP2ftseJxvO+f+8DB3A+Zi8DB3A+Zjc4Th3OM4z3eE4dzjOM93hOHc4zjPd4Th3OM4z3eE4dzjOM93hOHc4zjPd4Th3OM4z3eE4dzjOM93hOHc4zjPd4Th3OM4z3eE4dzjOM93hOHc4zjPd4Th3OM4z3eE479F/tx6og2Bff34AAAAASUVORK5CYII="></canvas>
```

My test is remapping the `read` value back onto a canvas: as a visual. And getImageData isn't a PNG, it's reading all the pixel values

Or I'm confused what you're trying to display

**Comment by kkapsner** [comment]
> My test is remapping the `read` value back onto a canvas: as a visual. And getImageData isn't a PNG, it's reading all the pixel values

That's what my "getImageData test" also does - the `title` attribute does not tell the canvas what to show: https://github.com/kkapsner/CanvasBlocker/blob/master/test/test.js#L7-L19

So I see a... wait - I know what the "problem" is: I read the whole canvas with `getImageData` and see the pattern. You read only one pixel at a time and as the pattern is different every time you read from it you get a complete random image.

**Comment by Thorin-Oakenpants** [comment]
Ahhh .. ummm .. am I doing it wrong then? Because it's definitely working to show spoofing patterns, and to detect randomizing per eTLD+1 (stealth randomizing)

but I think I get what you're saying ... if I read each pixel `1,1` back twice, I would get two different values (collisions excluded) - that would be for random per-execution like RFP, not random-per-session+eTLD+1 like Brave, or random like CB which is eLTD+1 while a tab of it is open ? Right?

**Comment by Thorin-Oakenpants** [comment]
> and as the pattern is different every time you read from it you get a complete random image

well, without re-SETTing the canvas, I could do a second `read` ...  but again, the randomness AFAICT depends on the spoofer: e.g. stealth mode, per-execution, etc.

The test was to detect randomness, which it does. And is used in TZP to check for added noise when and only if, the image isn't randomized per-execution. So I don't see the need to add a second read to the test

But yeah, the pattern thing makes more sense now

**Comment by Thorin-Oakenpants** [comment]
I'm confusing myself. This test is to fingerprint the spoofing pattern. Maybe a second read could be added. The test to detect noise is the other one, which uses a known result (here the expected result is known, but random on each test)

I still have work to do with this test: to bucketize the spoofing characteristics and return a `noise FP`

**Comment by Thorin-Oakenpants** [comment]
Hmmm ,,, maybe I should add the getImageData png as well

**Comment by Thorin-Oakenpants** [comment]
@kkapsner I'm ~~a little~~ quite brain dead right now

https://github.com/arkenfox/TZP/blob/a2a8b7715b6ce5a61796d2d239743264804ab7c5/tests/canvasnoise.html#L125-L126

`cnvCtrl` is the little canvas that we read from: e.g.

```js
				// toDataURL
				let dataURL = cnvCtrl.toDataURL("image/png")
				cnvURL.src = dataURL
```

what am I doing to get the getImageData PNG here?

![send-coffee](https://user-images.githubusercontent.com/16656956/97187613-85ac5c00-179a-11eb-916c-537a2a24e540.png)

PS: the "what we read back.." is ambiguous... it's "read" (red) past tense, not "read" present tense (reed) - that's probably not helping explain things very well

**Comment by Thorin-Oakenpants** [comment]
There you go, added a second read. If you flip CB to disable cache, it will return `[per-execution]` on the second read. If you re-enable cache in CB .. it will return `[cached]` on the second read  .. it only returns those if it's being spoofed

Just need that PNG filled in. I don't follow [this](https://github.com/kkapsner/CanvasBlocker/blob/master/test/test.js#L7-L19) .. you're passing `imageData` to the function ... what/where is `imageData`? is it an array of all the pixel values? [this is not helping me much](https://github.com/kkapsner/CanvasBlocker/commit/e65ac94dda7bf82d16248ddce2dff63ae95ff5d0)

time for a sleep 💤

**Comment by kkapsner** [comment]
`imageData` is an [imageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) like in `getImageData`

The interesting part is [here](https://github.com/kkapsner/CanvasBlocker/blob/master/test/canvasAPI.js#L35-L43).

Converting imageData to a PNG is not trivial without using a canvas... but what do you really want to achieve with this PNG?

**Comment by Thorin-Oakenpants** [comment]
... ☕  PNG is not the right word - thanks for the `putImageData`, that's what I was after :) Never bothered actually displaying it before

```js
				// getImageData
				let imageData = ctxCtrl.getImageData(0,0, cnvCtrl.width, cnvCtrl.height)
				ctxGet2.putImageData(imageData, 0, 0)

```

![done](https://user-images.githubusercontent.com/16656956/97250425-cee1c780-17fd-11eb-85ea-74dd13be0fe9.png)

now the test should explains exactly what is happening .. reads, pixel by pixel, doesn't use the word PNG, etc

**Comment by kkapsner** [comment]
Looks good.
