### ISSUE TITLE
canvas tests

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#15]
just some things (@abrahamjuliot )

* [x] [canvas spoofing detection](https://arkenfox.github.io/TZP/tests/canvasspoof.html)
   - For `toDataURL` and `toBlob`, I only check for a mismatch if it's FF or blink. These two engines output the PNG differently (and I know what the known result is for those two)
   - What would be nice is to know what Safari and iOS browsers return (i.e no spoofing)
*  [canvas spoof fingerprinting](https://arkenfox.github.io/TZP/tests/canvasnoise.html)
   - I plan on building on this to provide a stable noise FP
   - snip snip secret stuff .. you'll have to wait and see
   - sidenote: Brave seems to only ever modify ~~the `b`~~ a single random channel (random seed is eTLD+1 per session: session meaning while Brave is open)

**Comment by abrahamjuliot** [comment]
> canvas spoofing detection

Safari has the same hash on iOS and macOS. On browserstacks, I confirmed Chrome matches Safari. I'll get my hands on a iPad later this week and test iOS FF.

<details closed>
<summary>24c8af813fb7001ded7e81e125e9d3237e9400d5</summary>
<br>Safari macOS
<br><image src="https://user-images.githubusercontent.com/6946045/95147042-6cccff80-0734-11eb-9755-cc7119c4cd9f.png">
<br>browserstacks: iOS Safari (matches iOS Chrome)
<br><image src="https://user-images.githubusercontent.com/6946045/95145494-33929080-0730-11eb-8732-870230165fc3.png">
</details>

**Comment by Thorin-Oakenpants** [comment]
added webkit, and simulated an uncovered engine (so ignore my FF hash values). when the engine is not covered (blink, gecko, webkit), and we have a hash (rather than an error), then the unknown table row is shown, else it's hidden (to remove clutter)

![simulation](https://user-images.githubusercontent.com/16656956/95211173-c5a3a300-07db-11eb-8552-079d3e68f899.png)

**Comment by Thorin-Oakenpants** [comment]
hah: today's brave test

```
   cells changed: 81
channels changed: 2 [rb]
  channel counts: r: 1, g: 0, b: 80, a: 0
  combos altered: 2 [b, r]
    combo counts: {"r":1,"b":80}
```

so, when you account for collisions/anomalies(?) (i.e ignore counts under a certain threshold etc), it's still only changing the b channel (for FPing purposes). But I wonder what caused the single r to change - weird

**Comment by Thorin-Oakenpants** [comment]
just a quick update: brave's randomizing / seed determines a random channel. The seed is per session (per eTLD+1: i think it's +1). Despite probably about 25 different session brave tests over the last few weeks (not that I am working on brave issues), I've only ever seen the `b` channel, until yesterday, I got a `g` , and now it's back to `b`. Not sure what's going on there (and it's immaterial) as far I care

The thing is even if they randomized the single channel `per canvas`, or even `per execution`, I can still detect which channel is tainted: by using a large chunk of the canvas to detect that, and the rest of the canvas for the actual FP
