### ISSUE TITLE
prototype lies + chromium

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#151]
open chromium, no extensions
- load TZP
- chrome: zero prototype lies
- click the global rerun - now we have two lies: `Date.toString`, `Function.toString`
- click the global rerun again - now we have 182 lies

this is not normal. does not happen in Firefox

@abrahamjuliot

**Comment by abrahamjuliot** [comment]
That is my error. We just need to delete the test's fake property `""` in `getDefinePropertiesLie`. If it remains, then it pollutes the native function on the next run.

**Comment by Thorin-Oakenpants** [comment]
seems legit now, thanks :)
