### ISSUE TITLE
font stability: reminder remove Avenir Next Demi Bold

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#171]
ToDo
- [ ] mac: remove `Avenir Next Demi Bold`

---

this is concerning: mac has a very wonky first run (or first few runs?), so I built this
- https://arkenfox.github.io/TZP/tests/fontstability.html

You should run this with RFP off, and IDCare about TB, just use Firefox, so we cover the most fonts. The list is the same regardless: I just merged all the various lists per OS and de-duped and sorted. I am not checking all those "faces", we can reproduce instability in mac without those, and they may muddy the waters

Here is my windows on a cold app load: i.e open app, sanitized cache etc (I don't think sanitizing matters), and the very first site loaded is the test, which auto runs the first test - than manually re-run until stable

![stability](https://user-images.githubusercontent.com/16656956/173070320-ce065de7-9b14-4c27-97f3-50690d8b7929.png)

This is surprising, and hints at some sort of lazy/async loading. Maybe a bit like the fallback char mapping where it renders as tofu and catches up later.

The diffs are from the previous result, and are split into new (in the new result) and missing (in the new result)

**Comment by Thorin-Oakenpants** [comment]
I cold loaded, went to two websites: a twitter feed and LW matrix room, then loaded the test and it was stable first pop

I cold loaded the app again, waited 30 seconds, went to the test index then to the test and got a different result
```
RUN2 1 27cbaa83
"new:Arial Narrow, Calibri Light Italic",
```

**Comment by Thorin-Oakenpants** [comment]
I wonder if a dummy run with no dimension measuring before a font test would fix this - just on page load. Note; apparently the `font fallback` test is also wonky, at least on mac (and after multiple reruns on font test and font fallback test): not too worried about it, but it would have been handy to use that for diffs with the holy grail,

I also wonder if I can repro on creepy fonts tests (will have to check if has Arial Narrow, Arial Black, Calibri Light*, etc). But before I do anything, I want to see text results of wonky shit in mac

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot hey u `0xBADA55`, can you repro this?

**Comment by abrahamjuliot** [comment]
Win11 Nightly

![image](https://user-images.githubusercontent.com/6946045/173080878-f63a50c8-6388-4e7b-9725-cfc9f9f13096.png)

MacOS Beta (browserstack)

![image](https://user-images.githubusercontent.com/6946045/173081009-4fc1c096-7181-4562-a8a0-53dc7702a3f0.png)

**Comment by Thorin-Oakenpants** [comment]
Win11 ... but do you have Arial Black, Arial Narrow, Calibri Light`*`

https://bugzilla.mozilla.org/show_bug.cgi?id=1670199
- Arial Narrow (does not come with windows, but comes with at least MS Office)
- Calibri Light + Calibri Light Italic (optional win7 MS update) [1]

There's definitely something going on with these optional system fonts. They end up added to the font family (i.,e you ony have one `Arial` in `windows/fonts`, and it holds all these
- black, bold, bold italic, italic, narrow, narrow bold, narrow bold italic, narrow italic,  regular

And they're not false positives (narrow/black) because I do have them and others that don't never have them detected.

**Comment by abrahamjuliot** [comment]
> Arial Black, Arial Narrow, Calibri Light

Got all, but Arial Narrow. Actually, Arial Narrow is on the OS, but not detected in Firefox. I used the MS installation tool to create the build. It comes with the MS Office app, but no MS Office 365 desktop apps or the like.

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/TZP/commit/d441126c7901542ef451276de28d8a3a2548a25d

so using my `file://` scheme, I can consistently get an unstable first run in the test. On TZP I cannot get any instability - which is why I have never noticed it - this whole thing started because of mac instability BTW.

In the test, I have to be really quick, load FF, quick paste into URL bar, hit enter.

Once I added a setTimeout, which TZP has many of before the font test is run, I can no longer replicate. This however, does not fix the mac or underlying issue which I suspect is a timing/async/lazy loading font map thing

---

`Arial Narrow` .. ugh, one problem at a time :)

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/TZP/commit/d441126c7901542ef451276de28d8a3a2548a25d

actually, that makes no difference, and why should it. Doh. I actually think this is a delay caused by the OS reporting back to the app what fonts are available. I can reproduce easily (100%) on a cold portable - I have 50 odd portable FF's here. But then it gets harder to reproduce if tried again and again. But give the app a little downtime and it gets easier.

I guess the thing is, if fxbrit can reproduce easily on mac, then all that needs to be done is to see what could be run first to stop it - such as a priming run, or first adding a `<span>a</span>` for each font - offscreen - like [I did for the unicode glyphs](https://github.com/arkenfox/TZP/blob/6c774b2ee4ab62dd24b13116aab6e97f59f4b240/tzp.html#L59). Perf and especially reflow may be an issue

**Comment by Thorin-Oakenpants** [comment]
I've narrowed this down. It's absolutely the app and how it lazily loads _some_ fonts - AFAICT, there is no hard and fast rule as to how a font is handled, e.g. supplemental, font-family, initial, lazy - which would explain Arial Narrow and not Arial Black for example (both are inside the single `Arial` font-family file on windows) or Calibri Light (which is it's own font-family file, not inside Calibri). Font OS mapping, GDI etc is a mystery to me and I don't have 5 years to learn about it

So as you know, I have like 50 firefox portables with test profiles, and an older machine. ANd it's actually very easy for me to clear system caches, system memory to make a FF version load slow - takes 2 or 3 seconds to render and become usable - like if you had just booted the system

And I can test so fast, that I can usually paste the test file:// URL into the address bar and hit enter before the toolbar icons are rendered, and the test file:// URL is going to be faster than a live website. So I can 100% always reproduce instability

So I tested, bisecting until I found it started in FF90 - windows, super cold FF app, pasting and requesting file:// test even before toolbar icons populating
FF90
- [1707655](https://bugzilla.mozilla.org/1707655) Move the activation of supplemental fonts on macOS to a separate thread and try to get it started earlier
- [1708768](https://bugzilla.mozilla.org/1708768) Defer initialization of gfxPlatformFontList until really needed, to allow more time for the RegisterFonts thread to run
   - debug `sPlatformFontList` ?
   - I wonder what fonts on each platform are lazy loaded
   - `gfx.font-list.lazy-init.enabled` // renamed to omt (off main thread)
   - `gfx.font-list-omt.enabled` // false on windows FF90+

1708768 seems to indicate this was done for all platforms, and then the last patch (of the three) renamed the pref just for macOS. So I'm not 100% sure WTF is going on, because there's definitely some change in windows.

That pref is still around and default false on windows, and default true on mac. Look for it in searchfox if you want. Flipping it to false on macOS (just for testing, it's an old pref that hasn't moved for 13 versions and may cause weird bugs) might show that this is the cause on macOS. I obviously can't flip it on windows

So, waiting for the 🐟 fxbrit to reliably get instability and a list of fonts. And then he could test flipping that pref, even if he had to go back to an ESR91

**Comment by Thorin-Oakenpants** [comment]
also, the omt font list timing can differ per user, based on number of fonts = e.g. [1688951](https://bugzilla.mozilla.org/show_bug.cgi?id=1688951)

One question I have is how/when the "full" font list update. Is it when the omt list is done (soon after app start), or is it on demand, or on demand for each "omt" font? Can I get a list of omt fonts?

**Comment by Thorin-Oakenpants** [comment]
> AFAICT, there is no hard and fast rule as to how a font is handled, e.g. supplemental, font-family, initial, lazy

so [1773752](https://bugzilla.mozilla.org/show_bug.cgi?id=1773752) the [patch](https://phabricator.services.mozilla.com/D148944) is interesting, re font dirs, e.g. noto fonts, supplemental

there are no such dirs in windows, it's just `/windows/fonts/`

**Comment by fxbrit** [comment]
just to keep the info in this thread up to date as well, I've been testing on macos:
- 89, 90, ESR91, 92 -> they all look the same with 40 fonts in the diff
- 100, 101, 103 ->  they all look the same with 41 fonts in the diff
- ESR91.10 -> a single font in the diff
- `omt` does nothing
- setting `gfx.font_loader.delay` to 0 sends all the diffs to 0, except ESR91.10 which stays the same

**Comment by Thorin-Oakenpants** [comment]
- `gfx.font_loader.delay`: this is `60000` on windows, what is it on mac - just interested
- I will dig deeper into this, including [1284993](https://bugzilla.mozilla.org/show_bug.cgi?id=1284993), as to how it works _exactly_
- `gfx.*delay` - I only see 3 and all three are listed in that bugzilla
   - now we know the cause, testing these no longer matters: we can't change them: we need to work around them
- ESR91.10 -> a single font in the diff
   - what is that font? sounds like a different issue, and we could just exclude it from the lists as a known unstable item

So moving forward, I need to check a few things. I'd like to know when the delay ends and when the system fonts are updated to be available to web content. Let's say the timeout is 6 seconds, is this just from when the app boots and system fonts are updated regardless of web traffic etc, in a timely fashion

We could test this, (default prefs) by loading FF, waiting 30 seconds and then testing. If fonts are then stable, then this is not something we can really do anything about, or should - it's edge case?. If fonts are still unstable, then maybe we can nudge it to update by doing a priming run (and assuming 6 seconds have passed?). If the priming run fails, can we hardcode one of the known fonts to render in the HTML - as page content happens before scripts run. If that all fails, then we can just mark all those fonts as assholes and exclude them from tests?

Anyway, next test is what happens if you wait 30 seconds, no other web sites visits

**Comment by Thorin-Oakenpants** [comment]
41 fonts
```
Avenir Black, Avenir Black Oblique, Avenir Book, Avenir Heavy, Avenir Light, Avenir Medium, Avenir Next Condensed Demi Bold, Avenir Next Condensed Heavy, Avenir Next Condensed Medium, Avenir Next Condensed Ultra Light, Avenir Next Demi Bold, Avenir Next Heavy, Avenir Next Medium, Avenir Next Ultra Light,
Charter Black,
Hiragino Kaku Gothic Pro W3, Hiragino Kaku Gothic Pro W6,
Hiragino Kaku Gothic ProN W3, Hiragino Kaku Gothic ProN W6,
Hiragino Kaku Gothic Std W8, Hiragino Kaku Gothic StdN W8,
Hiragino Maru Gothic Pro W4, Hiragino Maru Gothic ProN W4,
Hiragino Mincho Pro W3, Hiragino Mincho Pro W6,
Hiragino Mincho ProN W3, Hiragino Mincho ProN W6,
Hiragino Sans GB W3, Hiragino Sans GB W6,
Hiragino Sans W0, Hiragino Sans W1, Hiragino Sans W2, Hiragino Sans W3, Hiragino Sans W4, Hiragino Sans W5, Hiragino Sans W6, Hiragino Sans W7, Hiragino Sans W8, Hiragino Sans W9,
Iowan Old Style Black"
```

**Comment by Thorin-Oakenpants** [comment]
so 8ms after startup, it's stable. Then I think this is just a known limitation that we can't do anything about. Would you agree?

**Comment by fxbrit** [comment]
yes, I think this is just the intended behavior of the browser. at least we know nothing is broken and also not to trust flawed results when testing fonts.

**Comment by Thorin-Oakenpants** [comment]
Indeed, all tests face the same issue. We've only landed on it because 1) you have a mac and 2) when testing we (and you) flip open a new session and are fast to load a test

> and also not to trust flawed results when testing fonts.

Well, to at least know ourselves that we should wait 8 seconds minimum

**Comment by Thorin-Oakenpants** [comment]
`Avenir Next Demi Bold` may come right in ESR102 (changes to SDK's, a bug fix? IDK) - in which case maybe it stays, since old releases become edge cases

**Comment by Thorin-Oakenpants** [comment]
>     * there exist more delay prefs (look for `gfx.*delay`) I haven't tested

FYI - [1786210](https://bugzilla.mozilla.org/show_bug.cgi?id=1786210) FF105+ `gfx.font_loader.interval` removed, it was a dead pref

**Comment by Thorin-Oakenpants** [comment]
also - https://bugzilla.mozilla.org/show_bug.cgi?id=1786209#c1

**Comment by fxbrit** [comment]
that explains why we only saw the delay in older ESRs, thx!

**Comment by Thorin-Oakenpants** [comment]
> ESR102 doesn't have the one font diff anymore 🎉

and that font diff was `Avenir Next Demi Bold` right? 

I am in the process of hooking up `isTZPSmart` (all engines) and `isTZPSmartMinVer` (min FF and TB version) is upped to v102, then no one cares

when not smart, TZP just reports the values returned: no lie detection/bypasses/notifications whatsoever. Fonts are also only isFF

```
	isTZPBlock = false,
	isTZPBlockMinVer = [78, 10], // [FF, TB version]
	isTZPSmart = false,
	isTZPSmartMinVer = [91, 91, 11], // [FF, TB, TB version]


	// block/smart
	if (isFF & isVer < isTZPBlockMinVer[0]) {isTZPBlock = true // block old gecko
	} else if (isEngine == "edgeHTML") {isTZPBlock = true // block edgeHTML
	} else if (isTB && isVer >= isTZPSmartMinVer[1]) {isTZPSmart = true // minTB
	} else if (isFF && isVer >= isTZPSmartMinVer[0]) {isTZPSmart = true // minFF
	}
	// note: everything else is dumb: we can add blink/webkit or brave later
```

I treat TB differently, because they can seriously lag in getting out a new stable based on ESR

so here I can set any browser to block based on any parameters (such as engine, FF version, isBrave, isTB etc), and if not blocked, then it's dumb by default: so I can switch on gecko as smart for starters, add isBrave later, maybe blink.

switching on isBrave will be fun: I can just hook up isBraveMode to every applicable metric and return lies. But first I'm going to make everything except gecko dumb

**Comment by fxbrit** [comment]
> and that font diff was Avenir Next Demi Bold right?

yup
