### ISSUE TITLE
font lists / font perf

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#197]
posting so I have a record somewhere

currently

#### WINDOWS - isPlatformFont (single pass vs MS Shell Dlg \\32 )

```
   all  219 (was 251)
   rfp   82 (was 115) (kBaseFonts - size collisions of expected)
    tb   83 (was 159) (whitelist - size collisions of expected)
```
todo:
- [x] keep trimming size collisions of expected fonts: e.g. "Cordia New", "CordiaUPC"
   - but make sure we keep at least one font from each of 8, 8.1, 10, 11
- [x] expand tb with bundled unique sizes
- [x] update with new win11 fonts - see [this](https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list)

---

#### MAC - isPlatformFont (single pass vs -apple-system)

```
   all  438 (this is too large)
   rfp  213 (kBaseFonts)
    tb   26 (whitelist - bundled (expected))
```

todo:
- [ ] expand tb with bundled unique sizes
- [ ] remove expected fonts with size collisions
- [ ] update with fonts from last two (or is it three?) macOS releases
   - including optional fonts (which makes the list excessively big)
   - did we add san francisco?
   - should we add symbol
- [ ] check if on mac when you add a "font", it adds all of them
   - e.g. if you add  "Gill Sans", does it auto add "Gill Sans Light","Gill Sans SemiBold","Gill Sans UltraBold"

---

#### LINUX

```
   all  467
    tb   60 (was all 134 bundled)
```

currently checks against 3 basefonts (but skips subsequent basefonts if already detected). And super large list sucks. It needs a clean out. I wonder if we could try and detect a known common font from a select list (not noto, we want as unique a size as possible) and use the first found of those so we can do a single pass

todo:
- [x] tb: just one of each size
- [x] tb: add isPlatformFont, e.g. Arimo (something unique) since we are restricted to an always expected 134 fonts ~~all fonts listed are expected so will be found on the first basefont anyway = same as a single pass~~ not quite true, most fonts will be found on the first pass, and if I know Noto fonts from android, it takes all three basefonts to get everything
   - this does not work, but it's OK, see https://github.com/arkenfox/TZP/commit/8ac97bf04f46001c4be22573aa1cf0f6ed5c83b7
- [ ] all: this is way too big: do some tests, remove shit old unlikely fonts, remove some size collisions if super common

---

#### ANDROID

```
   all  140
```

currently checks against 3 basefonts (but skips subsequent basefonts if already detected). It's not so bad at 140 fonts: e.g. my android finds 105 total: 100 or so on the first baseFont. But android is slow so anything here is a large gain

todo
- all: add more noto fonts
- all: reduce size collisions? yikes: this is noto, IDK what they results will be
- if widget font is Roboto, and Roboto is unique, then isPlatformFont it for a single pass
   - or is Android always Roboto and we can ignore when widget font is protected (like in TB)?

---

#### reminder

to build a test page to compare three pass detected to single pass detected

use this page to also output the size buckets

**Comment by Thorin-Oakenpants** [comment]
win11 new fonts

```
Cascadia Code ExtraLight
Cascadia Code ExtraLight Italic
Cascadia Code Light
Cascadia Code Light Italic
Cascadia Code SemiLight
Cascadia Code SemiLight Italic
Cascadia Code Regular
Cascadia Code Italic
Cascadia Code SemiBold
Cascadia Code SemiBold Italic
Cascadia Code Bold
Cascadia Code Bold Italic

Cascadia Mono ExtraLight
Cascadia Mono ExtraLight Italic
Cascadia Mono Light
Cascadia Mono Light Italic
Cascadia Mono SemiLight
Cascadia Mono SemiLight Italic
Cascadia Mono Regular
Cascadia Mono Italic
Cascadia Mono SemiBold
Cascadia Mono SemiBold Italic
Cascadia Mono Bold
Cascadia Mono Bold Italic

Segoe Fluent Icons

Segoe UI Variable Display Light
Segoe UI Variable Display Semilight
Segoe UI Variable Display Regular
Segoe UI Variable Display Semibold
Segoe UI Variable Display Bold
Segoe UI Variable Small Light
Segoe UI Variable Small Semilight
Segoe UI Variable Small Regular
Segoe UI Variable Small Semibold
Segoe UI Variable Small Bold
Segoe UI Variable Text Light
Segoe UI Variable Text Semilight
Segoe UI Variable Text Regular
Segoe UI Variable Text Semibold
Segoe UI Variable Text Bold

Sitka Banner Semibold
Sitka Banner Semibold Italic

Sitka Display Semibold
Sitka Display Semibold Italic

Sitka Small Semibold
Sitka Small Semibold Italic

Sitka Heading Semibold
Sitka Heading Semibold Italic

Sitka Subheading Semibold
Sitka Subheading Semibold Italic

Sitka Text Semibold
Sitka Text Semibold Italic
```

So which ones are font-families and which ones are faces?

@abrahamjuliot Do you have access to a Win11 machine with these fonts?

**Comment by abrahamjuliot** [comment]
I'm seeing these as font families [here](https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list). Matches my machine too.

```
Cascadia Code
Cascadia Mono
Segoe UI Variable Display
Segoe UI Variable Small
Segoe UI Variable Text
Segoe Fluent Icons
Sitka Banner
Sitka Display
Sitka Heading
Sitka Small
Sitka Subheading
Sitka Text
```

macOS Monterey fonts are now published. They are each Google Fonts.

https://support.apple.com/en-us/HT212587

```
K2D
Fahkwang
Charmonman
Chakra Petch 
Bai Jamjuree
Sarabun
Srisakdi
Kodchasan
KoHo
```

**Comment by Thorin-Oakenpants** [comment]
hmmm, that's weird .. doesn't seem to match other font naming conventions. Regular, you drop the `regular` part. Bold, Bold Italic and Italic are faces. Anything else is a font

Do you actually have in c:\\windows\fonts` ? - anyway, pinged you somewhere else with a full test
```
Cascadia Code ExtraLight
Cascadia Code Light
Cascadia Code SemiLight
Cascadia Code SemiBold
```

**Comment by abrahamjuliot** [comment]
correction: I'm confused. 

If I run this in Chrome, I get the above returned as font families

```js
console.log(await queryLocalFonts().then(fonts => [...new Set(fonts.map(font => font.family))].join('\n')))
```

Powershell also returns `Segoe UI Variable Display` as a family (no `Segoe UI Variable` family)

```
[System.Reflection.Assembly]::LoadWithPartialName("System.Drawing")
(New-Object System.Drawing.Text.InstalledFontCollection).Families
```


![image](https://user-images.githubusercontent.com/6946045/193186587-e0bfb7a2-b978-4905-907d-c835c60d92a6.png)

Font folder

![image](https://user-images.githubusercontent.com/6946045/193186912-6dee527a-7c6a-4723-805f-17b486d08c82.png)

![image](https://user-images.githubusercontent.com/6946045/193187089-ceaaf3c5-b199-42fb-81af-c5b63eaefdf0.png)

**Comment by abrahamjuliot** [comment]
FF Nightly

![image](https://user-images.githubusercontent.com/6946045/193189264-9da446cc-0060-4b46-aaee-208a97e306a6.png)

Chrome only works with "...Display" added

![image](https://user-images.githubusercontent.com/6946045/193189217-ce7b8e70-741c-4ef3-9584-b2a365d43552.png)

**Comment by Thorin-Oakenpants** [comment]
> Powershell also returns Segoe UI Variable Display as a family (no Segoe UI Variable family)
> Chrome only works with "...Display" added

right, there is no such font as `Segoe UI Variable` or `Segoe UI Variable Regular`. That's the way I see it. In actual fact, to be sure of the font name, you open the font in windows and read the title/name: e.g. 
- https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41307

**Comment by Thorin-Oakenpants** [comment]
wow, so nothing was detected from [all of these](https://github.com/arkenfox/TZP/blob/75963c16a034d405387a9ff741ae574c75e11b1e/js/fonts.js#L38-L56) ... yikes, WTF is going on

**Comment by abrahamjuliot** [comment]
Yeah, it seems these are not available apart from CSS Font Loading API.

**Comment by Thorin-Oakenpants** [comment]
Not even `Segoe Fluent Icons` ? The whole lot looks caputsky. I wonder if mozilla hasn't gotten around to adding them somewhere

I was planning on using the CSS Font Loading API to get win versions - I think you said it was super fast

**Comment by Thorin-Oakenpants** [comment]
that's some sweet perf on that mini vid bro. 90ms (with the console open, on nightly which is slower). I'm around 135 nightly and 125 stable - it's approx 50/50 between glyphs/textmetrics + fonts sizes - and that's on a 12yr old machine

**Comment by abrahamjuliot** [comment]
> sweet perf

Nice, I missed that. It's a custom tower. I think the fastest I can get on TZP is `178ms` and `68ms` on fonts. Actually, I mostly develop on this $100 Chromebook I got on eBay. It's stuck on Chrome 84, but I can test latest FF Android on it. I just remotely connect to more performant machines when I need to.

> `Segoe Fluent Icons`

Yep, missing.  Same in Chrome.

> CSS Font Loading API

It's fast, doesn't touch the DOM, and runs asynchronous.

```js
function getLocalFontFamily(font) {
    return new FontFace(font, `local("${font}")`)
        .load()
        .then((font) => font.family)
        .catch(() => null)
}

function loadFonts(fontList) {
    return Promise.all(fontList.map(getLocalFontFamily))
        .then(list => list.filter(font => font !== null))
}

loadFonts(['Segoe Fluent Icons']).then(fonts => console.log(fonts))
```

**Comment by Thorin-Oakenpants** [comment]
> It's fast

Great that it doesn't touch the DOM etc .. but this is not fast. I piped the default windows list of 219 fonts thru it and it took approx 200ms - but sure, on a few select fonts for extra entropy this can come in handy. By comparison, the getDimensions and touching the DOM takes approx 60ms, including an additional 10 base fonts and number crunching everything into pretty objects for FP storage

**Comment by abrahamjuliot** [comment]
It should speed up the overall script if run in a `Promise.all` execution. 

```js
 Promise.all([
   doSomeDomWork() // blocks other dom work or non-async operations (200ms)
   getFontFace() // runs in the event loop while doSomeDomWork() is running (200ms)
   getDomFonts() // waits for doSomeNonAsyncTask() to finish (50ms)
 ])
 
 // Overall time to complete ~250ms
 ```

**Comment by Thorin-Oakenpants** [comment]
a lot has changed in 2 years
- I sped fonts up recently by using objects rather than sets, each detected result was already unique as it included the font name (and base style if required)
- on a refresh, I got the collection of base sizes and font detection + sizes down from ~23ms to ~15ms .. for testing 201 fonts - not sure I can do much more
- unique sizes is interesting and I worked out how to increase it by mixing scripts
- unique sizes is not that important, and I reduced the fntString used to also speed up perf but return max unique sizes in almost all cases (OS and TB/FF)
- not going to reduce font lists to save perf, it's not worth it
   - for TB we can't as we need to ensure no fonts are missing
   - for FF: mac is speedy as they have top hardware so 400+ fonts is fine. And windows we can't drop much if we want to cover FPP and unexpected fonts for FPP
   - FF linux and android are a work in progress
- mac fonts are up to date as per Sequoia
- windows fonts have been up to date as of win 11 for ages
- android fonts got an overhaul from some moz telemetry data
- linux is a work in progress
   - might try and work FPP into it, but it's problematic
   - the easiest solution I think is to load up 50 VMs or something (https://www.osboxes.org/vmware-images/) and check the font lists and add some from each that are unique, as well as some common popular ones .. getting there

anyway .. closing ... thanks for listening :)
