### ISSUE TITLE
update isBrave / isBraveMode

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#209]
been like a year+ since we looked at this

https://github.com/arkenfox/TZP/commit/521ab0e57f5e2ed96e712611d271ce3051499967

this is now dependent on the shield mode
```
fileSystemAccessDisabled: !windowKeys.filter(key => fileSystemKeys.test(key)).length
```

so far nothing seems broken after my patch

things I/we can do
- [x] ~~note: in the isBrave checks, if we determine isBrave = true but the primary check `braveInNavigator` = false, I add this as a lie: not strictly necessary for entropy, since it will be reflected in the navigator keys array - but it's something people like to mess with and I like pointing out how stupid that is: hence why I check for all true but primary~~
   - scrapped: this is already reported as a lie in navigator keys if missing, we do not need to worry about hasPrimary - keep it simple
- [x] determine isBrave better
   - we don't need to use hashes
   - allow some flexibility
- [x] alert when isBrave but we have false results
   - an alert clickable link is shown top left when there are alerts, and they are added to the perf/debug details
   - special alerts like this one I also add output to `console.error`,
   - this is the only way for me to auto pick up when Brave changes something
- [ ] update/check our checklist for both isBrave and isBraveMode
   - e.g standard/strict now returns navigator.keyboard as null (which is very unusual)
   - e.g isBrave is now down to six items: is this enough

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot where are we at with all this?

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/TZP/commit/4703db07c721a2518b844ff71f7bce262fe30419

**Comment by Thorin-Oakenpants** [comment]
OT: https://mm.icann.org/pipermail/tz-announce/2022-September/000073.html (from https://bugzilla.mozilla.org/show_bug.cgi?id=1797248 ... these tzdata updates aren't useful for entropy (usually), they always get backported to ESR and we can already detect versions and engines)

> Simplify three Ukraine zones to one, since the post-1970 differences seem to have been imaginary.

_since post-1970_ ? .... holy cow ... so 50'ish years then ...

**Comment by Thorin-Oakenpants** [comment]
MOAR OT timey stuff
- https://news.ycombinator.com/item?id=33316941
- https://www.howderfamily.com/blog/australias-weird-little-time-zone/

a comment on the article mentions Broken Hill as also having a weird anachronism 

Anyway, Australian Central Western Standard Time (ACWST) which is what that article about is `Australia/Eucla` and yes, there is an `Australia/Broken_Hill` - both have unique timezone at https://arkenfox.github.io/TZP/tests/timezones.html

```
Australia/Broken_Hill

    8bc44a2ea49ad4cfd14a4943430a5a692717247d
    1879: -124.2, -124.2
    1921: -120, -120
    1952: -150, -150
    1976: -150, -150
    2018: -150, -150

Australia/Eucla

    37b22fa093e15c5e236caa7d37730509c274e979
    1879: -174.53333333333333, -174.53333333333333
    1921: -165, -165
    1952: -195, -195
    1976: -255, -195
    2018: -255, -195
```

and here's Nepal showing 45mins (as mentioned in the article) - i.e _minus_ 6hr, 15 minutes
```
Asia/Kathmandu

    117dd3a545aebb630f62b085604202af6f9107c2
    1879: -348.73333333333335, -348.73333333333335
    1921: -360, -360
    1952: -390, -390
    1976: -450, -390
    2018: -435, -375
```

**Comment by abrahamjuliot** [comment]
> @abrahamjuliot where are we at with all this?

Brave has a new Screen farbling available in Nightly by enabling `brave://flags/#brave-block-screen-fingerprinting`.

as far as I know:
 - does not change the visual viewport resolution
 - binds the screen resolution to the window outer resolution

way to bypass: 
- if brave + mobile, use the viewport resolution
- if brave + desktop, distrust the screen resolution if no taskbar is available

method to restore (slow): 
  - create an iframe with a `0x0` viewport (this can work with any preset resolution)
  - render the iframe on the page and get the screen resolution to obtain the offset values
  - subtract the offset values from the corresponding root window screen resolution values

There's also a font randomization, but it can be bypassed using `document.fonts.check('12px Consolas')`, for example.

**Comment by Thorin-Oakenpants** [comment]
yup, I know about the screen: not read it yet. It was mention by Arthur is test news 35 - https://privacytests.org/news.html - but I haven't looked into it

ATM, I am busy refactoring everything
- no smarts if isTZPSmart = false (almost there)
- no sha1 (almost there) - just use mini: everything was already mini, then some things were sha1 to get length
- no hashing `.join()` - we just hash the array or object (almost there)
- make each section and overall FP an object (almost there)
- make detail data (e.g. arrays/objects of lists of things like font sizes, css colors, whatever) into objects where appropriate - e.g. retain typeof (almost there)
- each section/overall FP contains the detail data (almost there)
- removal of "blocked" and treating it as lies: just trap errors and record them (halfway there)
   - e.g. if the error was X = not supported in versionY+ then we would report not supported, else we would report blocked, but only on FF, otherwise we would do something else = fuck this, just record the error = entropy in itself
- treat typeof mismatches as errors and record them (started)
- treat timeouts as errors and record them (mostly done)
- treat invalid results as errors and record them (started) - e.g. empty buffer arrays: when we expect a result but get nothing (not to be confused with a typeof mismatch)
- get rid of gMethods (almost done)
   - all errors, typeof mismatches, invalid results, timeouts = already recorded in the errors FP
   - anything "method" entropy such as domrect or canvas will be reported in that metric
      - domrect elements test is gone: instead we do a one-off prereq isClientRect test
      - canvas: will be replaced to ONLY be a protection test, and the results we be e.g. "RFP random", "stealth random", actualhash (if no lies) = no need for gMethods, as the method is in the metrics
- note: but we can still bypass errors: e.g. if matchmedia = errors, we can still read the css result
- errors are retained and shown per section run as well as global (done)
- lies + bypasses are retained and shown per section run as well as global (to do)
   - this makes it easier when I run simulations that cycle thru a set of results each section run, so I can check I am capturing and returning the right info/FPs
- logging all errors via a generic function (done)
   - which also returns a trimmed/max-length result for display
- logging all lies and bypasses via a generic function (to do)
   - i.e log_lies(name, bypassvalue) (if we can bypass something then there must be a lie, even if it was an "error")
- some other stuff, am losing track, send COVFEFE

simplifying code/processes. over the years of prototyping it has just gotten so inconsistent somewhat. The less thinking about isFF, is blocked, is supported, etc the better. And so much game theory going on with extensions and lies and bypasses. Sometimes the number of paraemeters in the logic makes my head spin.

Am working my way section by section, or sometimes by searching for key words in my code like " sha1(" or "zB0" or `.join(` etc. Bit of a mess TBH right now. But almost there.

When all that is finished and a PR done, then I can focus on isBraveMode lies/bypasses - atm it just returns things like math proofs (canvas), some of your stuff (plugins/mimetypes) and some isBraveMode stuff like hardwareConcurrency

isTZPSmart can be turned on and off per engine, per FF version, and by any other metric such as isBrave. I need to decide what I want to do. It's not hard to leverage isBrave + isBraveMode and point out all the randomizing/lies - but I would rather focus on FF and mathematical proofs and adding new items or improving current ones

**Comment by Thorin-Oakenpants** [comment]
@pes10k - last paragraph

> as far as I know
> ways to bypass

some quick notes off the top of my head
- mobile will always lack parity. Even RFP does not protect screen on android
- the viewport cannot be faked, RFP doesn't do this either. too many methods to measure it, and any BS will cause layout or other issues
- > binds the screen resolution to the window outer resolution
   - RFP binds to inner (and inner = outer), which I think is silly: I have been pushing to change this for years. On desktop, despite letterboxing, we should just report a sliding result depending on the inner height (don't care about orientation)
      - note: RFP has newwin protections
      - e.g. if height =< 1600 report 1600x900 (this means all RFP users on startup will be identical)
      - e.g. else if height =< 2560 report 2560x1440
      - e.g. else if ... 4k, else if 8k
      - i.e if users change the inner by maximizing or going fullscreen, it changes. If they revert, it changes back. Most users will not change the newwin (which is another story about the default newwin sizes)
      - this is not meant as a full protection, since inner is still entropy, but it makes screen less risky. scripts like screen as it is more stable, vs inner which is a shitshow (toggle chrome bits on or off, or accidentally resize, or zoom (zoom also affects screen) - in other words this helps reduce screen entropy on it's own down to 3 or 4 buckets, even for those who turn off letterboxing (and they do, even TB users)
- > applies a random offset distinct to each resolution coordinate
    - RFP just returns 0 for everything and it has been proposed as a standard IIRC, but sure, brave can farble it, why not, since the engineering is there

this I do not get (@pes10k) 
- > binds the screen resolution to the window outer resolution
   - I have not read what brave does exactly, so maybe something is missing here. This is a terrible idea. Look, outer and inner aren't exactly super stable, and while RFP ties to inner (and outer == inner with RFP), at least RFP has newwin size protections and letterboxing. So I'm sure Peter must be doing more than just the above sentence
- https://github.com/arkenfox/TZP/issues/209#issuecomment-1296537253 - see method to restore: those pesky iframes again

**Comment by pes10k** [comment]
could we add @arthuredelstein to this conversation, who is working on fingerprinting protections in Brave (and comes from Mozilla and Tor Browser)?

**Comment by arthuredelstein** [comment]
@Thorin-Oakenpants Hi! Why do you think binding the screen size to innerWidth/Height is silly?

I don't really follow the advantage of the approach you are proposing. The downside of your approach, it seems to me, is that if give a website screen dimensions that are too high, the website may attempt to open a window that is too large for the screen.

**Comment by Thorin-Oakenpants** [comment]
Hey Arthur!

To be clear, the "silly" (and not the best term I admit) was about RFP, where new windows are restricted to new tabs - to stop malicious window sizes. The initial RFP protection, of which you were a part, was newwin (on creation) sizes of 1000 x 1000 px max, outer == inner, screen + available screen = inner. There was no letterboxing. And android TB didn't exist (and is different anyway)

One issue with this is that any change in inner affects reported screen. Screen is a stable metric (aside from zooming) that scripts love. Inner is for advanced scripts and is less stable. i.e while attempting to make as few screen buckets as possible, by limiting to the same as inner (and we assume advanced scripts in Tor Browser), we have also made it somewhat fragile - cue newwin size bugs etc. Or users resizing accidentally, even by a smidgen. So we have a dozen newwin sizes, plus bugs, plus users changing the size (chrome changes toggling bits on and off like sidebar or menu, maximizing, full-screen, manual, etc). All of which affect screen. Yes, inner is still measurable, but the screen buckets are affected - think of scripts that don't get or try to use inner to link.

Additionally, there are some RFP orientation patches, which TBH are incomplete.

Now picture what I suggested - desktop only of course. Screen (and available screen) is limited to e.g. 2k, 4k, 8k, end of. story - 3 buckets. Or 4 buckets. Or 5 buckets. As long as all newwins are under the smallest res/bucket. All scripts that only get/use screen and/or available screen will now have all TB users in a single bucket on that metric. If a user exceeds the size, we step up one - I like this as it can create a different FP if the user maximizes for example.

Now letterboxing is still great and it limits the entropy in inner (and outer) sizes. But it's still tied to screen. The sliding LB steps of 50px, 100px, 200px width and 100px height, allow for a LOT of buckets. Certainly nothing like the 1px steps, but it's still a lot. By decoupling screen from matching inner, we can reduce potential screen buckets from a million+ (no letterboxing) to hundreds? (letterboxing) to 3 or 5 (just step several sizes). And we can reduce screen buckets on startup from a dozen+ or whatever it is (1000x600, 1000x700, 1000x800, etc 900x800, 900x700, etc) to one bucket.

This literally cannot increase entropy, it can only reduce it, and only on scripts that don't use inner. Letterboxing we keep for inner protection. It would also remove the necessity of RFP orientation spoofing, which is incomplete and was discussed as being done away with - as we would always be reporting landscape anyway

And another reason to not tie to inner, is that round hundred screen sizes is used in the wild to detect TB - why make it easy for them. So, in the bigger picture, while it does nothing for advanced scripts, it does mitigate the risk and is a first step in being able to re-evaluating newwin sizes for usability (1000px width is not sufficient on desktop these days and most screens are widescreen, we can at least increase the max width without any (or very minimal) inner entropy loss IMO but I need to crunch the numbers properly - i.e smaller res non 16/9 screen already have their own buckets)

maybe I'm terrible at explaining things, because while not super high priority, I don;t get why no-one else sees this, and it's trivial to implement

---

Now for Brave. As I said, I have not read _what_ you have done. So when abraham commented "binds the screen resolution to the window outer resolution" and nothing more with that metric (they other bullet points were about coordinates and viewport), I said surely there must be more. Just reporting someone's unprotected outer window size is not the answer.

I didn't mean that using outer as a starting point was "terrible" (we need to start with something based in reality - RFP uses inner), I meant if that was it, then it was "terrible"  -  surely there must be more going on? Which is why I said "I have not read what brave does exactly, so maybe something is missing here"

RFP is based on inner (or outer if you like since they are the same), but at least RFP has newwin, and letterboxing, and TB forces new windows to open as new tabs.

So I would expect Brave to be doing at least something else with screen metrics

**Comment by Thorin-Oakenpants** [comment]
> The downside of your approach, it seems to me, is that if give a website screen dimensions that are too high, the website may attempt to open a window that is too large for the screen

to be clear, as per last post
> RFP, where new windows are restricted to new tabs - to stop malicious window sizes.

**Comment by arthuredelstein** [comment]
> To be clear, the "silly" (and not the best term I admit)

No worries at all. :) Just trying to understand, and I appreciate the feedback.

> Now for Brave. As I said, I have not read _what_ you have done. So when abraham commented "binds the screen resolution to the window outer resolution" and nothing more with that metric (they other bullet points were about coordinates and viewport), I said surely there must be more. Just reporting someone's unprotected outer window size is not the answer.

> I didn't mean that using outer as a starting point was "terrible" (we need to start with something based in reality - RFP uses inner), I meant if that was it, then it was "terrible" - surely there must be more going on? Which is why I said "I have not read what brave does exactly, so maybe something is missing here"

In Brave's protection, APIs are actually bound to the original inner (not to outer). You can see a full summary at https://github.com/brave/brave-core/commit/e63185989b457dc01152b165d527efa5188e408c. The goal of that work is strictly to hide hardware characteristics. I hope that clears up our approach, but let me know if anything isn't clear. (@abrahamjuliot's "method to restore" is very interesting and I will look into it.)

I think of the viewport size problem to be a (mostly) separate problem from screen size. It is quite challenging because of the UX implications and likely should be lower priority than some other fingerprinting problems.

**Comment by Thorin-Oakenpants** [comment]
> I think of the viewport size problem to be a (mostly) separate problem from screen size

exactly. which is why (not your problem) I think TB/RFP should decouple them. once they do that, it enables better solutions - that was what I was getting at

> You can see a full summary

OK. That shows farbling. So it was more than just tying to inner

> "method to restore" is very interesting

but wait .. I see no css protection... in which case, TZP should bypass it already (range 500 to 2560 px)

**Comment by arthuredelstein** [comment]
> > You can see a full summary
> 
> OK. That shows farbling. So it was more than just tying to inner

Yes, tying to inner plus a small random offset.

> > "method to restore" is very interesting
> 
> but wait .. I see no css protection... in which case, TZP should bypass it already (range 500 to 2560 px)

CSS protection is the third item in that commit message:
```
3. device-{width,height} in media queries

When farbling is enabled, media query for device-width
matches the same value as window.screen.width (also farbled).
Same for device-height.
```

**Comment by Thorin-Oakenpants** [comment]
https://arkenfox.github.io/TZP/tzp.html#screen

I have
- `[css min-device-] screen resolution` (I use min because on devices with subpixels it usually drops 1 pixel)
- `[matchMedia] screen resolution` - on devices with subpixels this may not be an integer

my bad, I read `media queries` in my head as matchmedia/JS

I assume you covered all possible css queries? I guess I can wait til the patch hits stable release, but I don't check Brave often (the other day was the first time in like six months) and while TZP is aimed at gecko, a lot is still in common

I'll leave it all to you - you know what needs to be done, having been part of TB + RFP. If I see anything in future in my tests, Peter knows where I reveal them "-)

**Comment by arthuredelstein** [comment]
> I assume you covered all possible css queries?

The only css queries that commit covers is device-width/device-height, which reveal screen size (through media queries and matchMedia). If you know of any other css query I might have missed that reveals screen size, please let me know!

**Comment by Thorin-Oakenpants** [comment]
^^^ look up ... .`css min-device-`

**Comment by arthuredelstein** [comment]
Yes, `min-device-width/height` and `max-device-width/height` is also covered.

**Comment by arthuredelstein** [comment]
Hi @abrahamjuliot, I'm interested in this technique:

> method to restore (slow):
> * create an iframe with a 0x0 viewport (this can work with any preset resolution)
> * render the iframe on the page and get the screen resolution to obtain the offset values
> * subtract the offset values from the corresponding root window screen resolution values

I tried to reproduce this but couldn't. Do you have a working example I could look at?

**Comment by abrahamjuliot** [comment]
Sure. I'm finding this detection is not that great. 😢 It only restores the inner resolution, which can instead be accessed directly with `innerWidth` and `innerHeight`. 

```js
// iframe method (slow)
;(() => {
  const presetWidth = 1920
  const presetHeight = 1080

  const iframe = document.createElement('iframe')
  iframe.width = presetWidth
  iframe.height = presetHeight
  
  document.body.appendChild(iframe)
  const { width, height } = iframe.contentWindow.screen
  document.body.removeChild(iframe)
  
  const offsetHeight = height - presetHeight
  const offsetWidth = width - presetWidth
  
  console.log('offset:..', ''+[offsetWidth, offsetHeight])
  console.log('inner:...', ''+([innerWidth, innerHeight]))
  console.log('screen:..', ''+([screen.width - offsetWidth, screen.height - offsetHeight]))
})()

// matchMedia method (fast)
;(() => {
  const matches = (x, query) => matchMedia(`(device-${query}: ${x}px)`).matches
  let offsetHeight = 0
  let offsetWidth = 0
  
  while (offsetHeight < 10 && !matches(window.innerHeight + offsetHeight, 'height')) offsetHeight += 1
  while (offsetWidth < 10 && !matches(window.innerWidth + offsetWidth, 'width')) offsetWidth += 1
  
  console.log('offset:..', ''+[offsetWidth, offsetHeight])
  console.log('inner:...', ''+([innerWidth, innerHeight]))
  console.log('screen:..', ''+([screen.width - offsetWidth, screen.height - offsetHeight]))
})()

```

**Comment by Thorin-Oakenpants** [comment]
closing .. isBrave was hardened and I added some alerts for when something changes .. job done .. back to focusing on gecko
