### ISSUE TITLE
Privacy Preserving Attribution

### ISSUE THREAD

**Issue by sertonix** [arkenfox/TZP#319]
When PPA is disabled the functions are a no-op. This skips the argument checking too so it is possible to detect whenever or not PPA is enabled. From what I have seen it should be possible to hide whenever PPA is enabled or disabled.

```js
let enabled = false;
try {
  // The ~ is considered an invalid url and will cause an error when PPA is enabled.
  navigator.privateAttribution.saveImpression({ type: "view", index: 6, ad: "shoes", target: "~" });
} catch (e) {
  if (e instanceof DOMException)
    enabled = true;
}
```

Since PPA is an [Origin Trial](https://wiki.mozilla.org/Origin_Trials) you currently need to set `dom.origin-trials.private-attribution.state: 1` for the API to be available on any website.

**Comment by Thorin-Oakenpants** [comment]
AFAICT ... when this becomes available on any website ... this is not a thing
- see `https://github.com/mozilla/explainers/issues/11#issuecomment-2228913120`

**Comment by sertonix** [comment]
Then this is a bug. Made a report here https://bugzilla.mozilla.org/show_bug.cgi?id=1908470

**Comment by Thorin-Oakenpants** [comment]
sorry, I have a lot going on and am not really following this

**Comment by Thorin-Oakenpants** [comment]
I honestly can't quite follow this - I tried the other day in nightly with it enabled and not enabled and couldn't detect a difference (using console on live web sites)

**Comment by sertonix** [comment]
Setting `dom.origin-trials.private-attribution.state` to `1` enables the API for all sites. This is needed cause the API is experimental (and the other options are too complicated).

**Comment by Thorin-Oakenpants** [comment]
okie dokie - soz, am super busy with TB stuff - ESR128 is a huge jump :)
