### ISSUE TITLE
canvas perf & RFP

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#36]
OK, I finally bothered to work out the massive perf issue with RFP = true - surprise, it's canvas. Perf here being the overall TZP figure at the top

in my nightly
- set RFP - true
- make sure to not clear site exceptions on close, but clear everything else (e.g. cache)
- load TZP
- close FF, reopen, visit, etc
- perf is always around 1900 to 2100 ms (for me)

now set a canvas site exception for TZP and repeat test (close, open, load tzp etc)
- perf is always around 1100-1300 for me
- same as if I run it locally as `file://` - because RFP does not change canvas in `file:///`

disable RFP and repeat test
- non RFP is always around 1100-1300 for me

So clearly RFP canvas is a perf hog: note I'm running each canvas test twice to detect random per execution, as well as the tampering tests (i.e comparing to known results) at the same time in case it's stealth spoofing (per session/eTLD+1 etc)

---

Possible solutions
- get upstream to look at the perf, IDK ... probably not that important and probably already performant as possible
   - @tomrittervg ^^ for you
- bypass the tests
   - Step 0: detect Firefox version (already done)
   - Step 1: detect if RFP is on in (can do: takes about 1ms)
   - Step 2: if RFP is on and version > FF77, then do a single small known result test to see if the result is spoofed and matches the RFP spoofing FP
   - Step 3: if step two says RFP-type spoof, then just return that it's all random per pass, otherwise do the actual test

Note: I will have to check that this perf issue wasn't in FF77 or lower (when RFP returned a static value)

What do you guys think about skipping actual tests based on deterministic analysis? IDK if I'm keen on that. I would rather show and prove that it's random per pass on each API call/method etc

**Comment by Thorin-Oakenpants** [comment]
> Note: I will have to check that this perf issue wasn't in FF77 or lower (when RFP returned a static value)

confirmed: it's the randomizing in FF78+ that is the cause

**Comment by tomrittervg** [comment]
So how many times are you calling canvas extraction?

**Comment by Thorin-Oakenpants** [comment]
@tomrittervg : 15

3 calls (passes 1 + 2, and a third call to compare known results)
https://github.com/arkenfox/TZP/blob/25c6356e98fcf8666f14a84440f03bb58e7b3cfd/js/canvas.js#L571-L575

times 5 measurments ( toDataURL, toBlob, etc)
![canvas](https://user-images.githubusercontent.com/16656956/104748193-5843ce80-5749-11eb-97b1-6745fd0e1aaf.png)

**Comment by Thorin-Oakenpants** [comment]
since isPoint is static, I think we can ignore those, so the real answer would be 3 x 3 = 9

**Comment by Thorin-Oakenpants** [comment]
I added some timing in my local version: this is RFP off, page load

page load (obv. other sections/functions are running): canvas section took 813ms
```
toDataURL [1] 1 ms
getImageData (minus SHA-256) [1] 61 ms
toDataURL [2] 0 ms
getImageData (minus SHA-256) [2] 8 ms
toBlob [1] 799 ms
toBlob [2] 729 ms
```



re-run: canvas section took 143 ms
```
toDataURL [1] 1 ms
getImageData (minus SHA-256) [1] 30 ms
toDataURL [2] 0 ms canvas.js:203:15
getImageData (minus SHA-256) [2] 10 ms
toBlob [1] 135 ms
toBlob [2] 88 ms
```

I'll create a standalone test, add in the third pass (known results) and upload. And report back the results

**Comment by Thorin-Oakenpants** [comment]
@tomrittervg 

You can test yourself. logPerf is enabled, and I've added all the canvas calls `[1]` 1st call `[2]` 2nd call `[k]` the known test - just filter for `canvas` to avoid the noise
- left RFP = off, right RFP = on
- test is sanitized FF (no cached etc), open FF, load TZP
- first result is TZP loading, the second result (I broke it with a debug command) is a canvas section re-run
- time columns: first column is since the `outputCanvas()` function was called (ignore the second column)
- NOTE: even if the only thing to run on the page ever was the canvas section, canvas still takes about the same time: anyway, the section rerun on it's own shows about a doubling+ of time taken with RFP

![canvasperf](https://user-images.githubusercontent.com/16656956/104828261-5409d500-585f-11eb-92e1-932bd742827f.png)

**Comment by Thorin-Oakenpants** [comment]
OK, I don't think it helps to bombard the console with warnings: sometimes it's a group of 250 warnings and nothing else, but others it lags everything  and in this case the number is 4378 warnings .. **_not grouped_** in any way shape or form

![console-spam](https://user-images.githubusercontent.com/16656956/105035149-7152c500-5a52-11eb-884d-5f839f8bb4d1.png)

**Comment by Thorin-Oakenpants** [comment]
anecdotal : on my android
 - test: clear everything, load TZP, wait for it to load, scroll down, test the canvas section rerun several times
 - RFP off: reruns are `130-150`ms
 - RFP on: reruns are `800-900`ms

**Comment by Thorin-Oakenpants** [comment]
OK, this is not super accurate per method (see https://github.com/arkenfox/TZP/issues/54#issuecomment-809075334). But it's good enough to show *something* is causing a slow down. This is purely canvas section re-runs: so no other code is being run at the same time

this is using some console.info output with timestamps

### RFP off

with RFP off (and no extensions interfering), it's typically 75-80ms
- here you can see it's about `70ms` from the first info for everything except toBlob
- and then the toBlobs instantly follow

```
06:43:03.605         toDataURL [1] [canvas]:    2 ms |    8 ms
06:43:03.610      getImageData [1] [canvas]:    2 ms |   14 ms
06:43:03.611     isPointInPath [1] [canvas]:    1 ms |   15 ms
06:43:03.619   isPointInStroke [1] [canvas]:    7 ms |   22 ms
06:43:03.623         toDataURL [2] [canvas]:    3 ms |   26 ms
06:43:03.627      getImageData [2] [canvas]:    2 ms |   31 ms
06:43:03.628     isPointInPath [2] [canvas]:    1 ms |   32 ms
06:43:03.635   isPointInStroke [2] [canvas]:    7 ms |   39 ms
06:43:03.639         toDataURL [k] [canvas]:    2 ms |   42 ms
06:43:03.671      getImageData [k] [canvas]:   31 ms |   75 ms
06:43:03.673     isPointInPath [k] [canvas]:    1 ms |   77 ms
06:43:03.674   isPointInStroke [k] [canvas]:    1 ms |   78 ms
--- 69ms
06:43:03.676            toBlob [1] [canvas]:   71 ms |   80 ms
06:43:03.677            toBlob [2] [canvas]:   55 ms |   81 ms
06:43:03.677            toBlob [k] [canvas]:   39 ms |   82 ms
```

### RFP ON

And here are three examples of RFP = on: it's typically double plus a long wait for toBlob
- here you can see it's about `160ms` from the first info for everything except toBlob
- and then the toBlobs hang around for `400+ ms`

```
17:32:12.090         toDataURL [1] [canvas]:    0 ms |    0 ms
17:32:12.095      getImageData [1] [canvas]:    0 ms |  100 ms
17:32:12.111     isPointInPath [1] [canvas]:    0 ms |  100 ms
17:32:12.127   isPointInStroke [1] [canvas]:    0 ms |  100 ms
17:32:12.129         toDataURL [2] [canvas]:    0 ms |  100 ms
17:32:12.134      getImageData [2] [canvas]:    0 ms |  100 ms
17:32:12.149     isPointInPath [2] [canvas]:    0 ms |  100 ms
17:32:12.165   isPointInStroke [2] [canvas]:  100 ms |  200 ms
17:32:12.167         toDataURL [k] [canvas]:    0 ms |  200 ms
17:32:12.238      getImageData [k] [canvas]:  100 ms |  300 ms
17:32:12.245     isPointInPath [k] [canvas]:    0 ms |  300 ms
17:32:12.251   isPointInStroke [k] [canvas]:    0 ms |  300 ms
   161ms from first message above
 + 423ms to Blobs
17:32:12.674            toBlob [1] [canvas]:  500 ms |  600 ms
17:32:12.674            toBlob [2] [canvas]:  500 ms |  600 ms
17:32:12.674            toBlob [k] [canvas]:  400 ms |  600 ms

17:33:02.391         toDataURL [1] [canvas]:    0 ms |    0 ms
17:33:02.396      getImageData [1] [canvas]:    0 ms |    0 ms
17:33:02.412     isPointInPath [1] [canvas]:    0 ms |    0 ms
17:33:02.428   isPointInStroke [1] [canvas]:    0 ms |    0 ms
17:33:02.430         toDataURL [2] [canvas]:    0 ms |    0 ms
17:33:02.434      getImageData [2] [canvas]:    0 ms |    0 ms
17:33:02.450     isPointInPath [2] [canvas]:  100 ms |  100 ms
17:33:02.466   isPointInStroke [2] [canvas]:    0 ms |  100 ms
17:33:02.468         toDataURL [k] [canvas]:    0 ms |  100 ms
17:33:02.540      getImageData [k] [canvas]:    0 ms |  100 ms
17:33:02.547     isPointInPath [k] [canvas]:    0 ms |  100 ms
17:33:02.553   isPointInStroke [k] [canvas]:    0 ms |  100 ms
   162 from first message above
 + 418ms to Blobs
17:33:02.971            toBlob [1] [canvas]:  500 ms |  500 ms
17:33:02.971            toBlob [2] [canvas]:  500 ms |  500 ms
17:33:02.972            toBlob [k] [canvas]:  400 ms |  500 ms

17:33:21.740         toDataURL [1] [canvas]:    0 ms |    0 ms
17:33:21.745      getImageData [1] [canvas]:    0 ms |    0 ms
17:33:21.761     isPointInPath [1] [canvas]:    0 ms |    0 ms
17:33:21.777   isPointInStroke [1] [canvas]:    0 ms |    0 ms
17:33:21.779         toDataURL [2] [canvas]:    0 ms |    0 ms
17:33:21.784      getImageData [2] [canvas]:    0 ms |    0 ms
17:33:21.800     isPointInPath [2] [canvas]:    0 ms |    0 ms
17:33:21.815   isPointInStroke [2] [canvas]:    0 ms |    0 ms
17:33:21.817         toDataURL [k] [canvas]:    0 ms |    0 ms
17:33:21.889      getImageData [k] [canvas]:    0 ms |    0 ms
17:33:21.896     isPointInPath [k] [canvas]:    0 ms |    0 ms
17:33:21.902   isPointInStroke [k] [canvas]:    0 ms |    0 ms
   162 from first message above
  + 400ms to Blobs
17:33:22.303            toBlob [1] [canvas]:  500 ms |  500 ms
17:33:22.303            toBlob [2] [canvas]:  500 ms |  500 ms
17:33:22.304            toBlob [k] [canvas]:  500 ms |  500 ms
```

**Comment by Thorin-Oakenpants** [comment]
totally unscientific :) no consoles open BTW (I have a theory this causes a slowdown as well)

### RFP on

new sanitized session
 - overall 1300-1400, canvas 100-200
 - rerun canvas section: 200
- now do a global rerun
 - overall 1100, canvas 200
- rerun canvas section: 200

reload the page
- overall 1100, canvas 200
 - rerun canvas section: 200
- now do a global rerun
 - overall 1000, canvas 200
- rerun canvas section: 200

### RFP off

new sanitized session
 - overall 1200-1350, canvas 125'ish <-- did this a half dozen times
    - NOTE: this drops back to almost normal if canvas was recently used?
    - e.g. first visit tests/canvasspoof.html or tests/canvasnoise.html
 - rerun canvas section: various 70-100
- now do a global rerun
 - overall 956, canvas ~75
- rerun canvas section: various 70-100

reload the page
- overall 983, canvas ~70
 - rerun canvas section: various 70-100
- now do a global rerun
 - overall 962, canvas ~70
- rerun canvas section: various 70-100

### conclusions

- on page load there doesn't seem to be much difference: both overall and canvas (if canvas hasn't been used recently)
   - ignore page loads, there are too many variables: e.g. with RFP on, page load was 1300 (which is comparable) but canvas at 300 (which sounds high)
- on refresh, global & section reruns, it looks like canvas takes about double

Faster without RFP (refresh page, reruns) = something to do with memory and GC
Not faster with RFP = because everything is randomized so it's always like a new one
I wonder if there is anyway to force a GC to test that?

**_So if I understand this correctly, what I'm seeing is non-RFP canvas gets a perf boost when reused, NOT that RFP canvas is slow_**
