### ISSUE TITLE
system styles

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#53]
@abrahamjuliot 

So I had a look at your system styles

I compared your details to mine
```ts

ON CREEPY, NOT ON TZP
----------
ButtonBorder: rgba(0, 0, 0, 0)
Mark: rgba(0, 0, 0, 0)
MarkText: rgba(0, 0, 0, 0)


7 CSS4: matching count + values
----------
ActiveText: rgb(238, 0, 0)
Canvas: rgb(255, 255, 255)
CanvasText: rgb(0, 0, 0)
Field: rgb(255, 255, 255)
FieldText: rgb(0, 0, 0)
LinkText: rgb(0, 0, 238)
VisitedText: rgb(85, 26, 139)

28 SYSTEM: matchng count + values
----------
0		ActiveBorder: rgb(180, 180, 180)
1		ActiveCaption: rgb(153, 180, 209)
2		AppWorkspace: rgb(171, 171, 171)
3		Background: rgb(0, 0, 0)
4		ButtonFace: rgb(240, 240, 240)
5		ButtonHighlight: rgb(255, 255, 255)
6		ButtonShadow: rgb(160, 160, 160)
7		ButtonText: rgb(0, 0, 0)
8		CaptionText: rgb(0, 0, 0)
9		GrayText: rgb(109, 109, 109)
10	Highlight: rgb(51, 153, 255)
11	HighlightText: rgb(255, 255, 255)
12	InactiveBorder: rgb(244, 247, 252)
13	InactiveCaption: rgb(191, 205, 219)
14	InactiveCaptionText: rgb(67, 78, 84)
15	InfoBackground: rgb(255, 255, 225)
16	InfoText: rgb(0, 0, 0)
17	Menu: rgb(240, 240, 240)
18	MenuText: rgb(0, 0, 0)
19	Scrollbar: rgb(200, 200, 200)
20	ThreeDDarkShadow: rgb(105, 105, 105)
21	ThreeDFace: rgb(240, 240, 240)
22	ThreeDHighlight: rgb(255, 255, 255)
23	ThreeDLightShadow: rgb(227, 227, 227)
24	ThreeDShadow: rgb(160, 160, 160)
25	Window: rgb(255, 255, 255)
26	WindowFrame: rgb(100, 100, 100)
27	WindowText: rgb(0, 0, 0)

system fonts: TZP
----
caption:Segoe UI 12px
icon:Segoe UI 12px
menu:Segoe UI 12px
message-box:Segoe UI 12px
small-caption:Segoe UI 12px
status-bar:Segoe UI 12px
-moz-window:Segoe UI 12px
-moz-desktop:Segoe UI 12px
-moz-document:Segoe UI 12px
-moz-workspace:Segoe UI 12px
-moz-info:Segoe UI 12px
-moz-pull-down-menu:Segoe UI 12px
-moz-dialog:MS Shell Dlg \\32  12px
-moz-button:MS Shell Dlg \\32  13.3333px
-moz-list:MS Shell Dlg \\32  13.3333px
-moz-field:MS Shell Dlg \\32  13.3333px


system fonts: creepy
-----
caption:
icon:
menu:
message-box:
small-caption:
status-bar: 
```

So I think I've answered my question: I have everything you have, except three "system" colors
- `ButtonBorder`, `Mark`, and `MarkText` - note the values: `rgba(0, 0, 0, 0)`
- I think these are deprecated ❔ ❓ I do not see them in the link below

And you have the same as me, except
- I have 68 `-moz-` colors (seven are aliases to matching system colors)
- I have additional `-moz-` system fonts
- my system fonts have a font name and size

I also had 36 "skippable" system colors, but pulled them. When queried they simply got the previous value. They were removed a long time ago I think

here's a [firefox link](https://searchfox.org/mozilla-central/rev/1a47a74bd5ba89f2474aa27c40bd478e853f3276/servo/components/style/values/specified/color.rs#151) for you

Anyway, let me know if this improves your data, and if I'm missing anything :) Have some 🍨

**Comment by abrahamjuliot** [comment]
Thanks 🙏, I'm finally getting around to fixing the blank system fonts in FF on creepy.

**Comment by Thorin-Oakenpants** [comment]
wtheck is that emoji? looks like a banana split with two scoops of ice cream .. or a runny nose ... or a dick with [blue balls](https://en.wikipedia.org/wiki/Blue_balls) 😀 

I looked [here](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md) but couldn't spot it

nvm .. folding hands .. I preferred when editing showed `:name:`

**Comment by abrahamjuliot** [comment]
😂
note to self: maybe not use that emoji next time
