### ISSUE TITLE
trap resource:// blocking

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#54]
I make sure several global vars are set before we start fingerprinting: such as isFF, isOS, isTB, isEngine, prototype lies. Unfortunately, isTB never resolves with cydec (at least in total mode), and thus the promise never happens and we have no output: section re-runs work sweet :)

note: isTB is initially an empty string = "", and I set it once to a boolean. I do not have any instances of `(!isFF)`. TB shouldn't have any extensions that cause the script to break, so I'm happy to trap this and change isTB into false based on assumptions

note: this is the only `resource://` that is set via code. The only other one is an image set via css: and that function works on the same assumption: if it's there = TB, if it isn't = not TB.

here is the code
```js
function get_isTB() {
	return new Promise(resolve => {
		if (isFF && isTB === "") {
			try {
				let t0 = performance.now()
				console.debug("a")
				let css = document.createElement("link")
				console.debug("b")
				css.href = "resource://torbutton-assets/aboutTor.css"
				css.type = "text/css"
				css.rel = "stylesheet"
				console.debug("c")
				document.head.appendChild(css)
				console.debug("d")
				css.onload = function() {
					isTB = true
					debug_page("TB","     resource:// = aboutTor.css")
					if (logPerf) {debug_perf("[yes] isTB [immutables]",t0)}
					return resolve("done")
				}
				css.onerror = function() {
					isTB = false
					if (logPerf) {debug_perf("[no] isTB [immutables]",t0)}
					return resolve("done")
				}
				document.head.removeChild(css)
			} catch(e) {
				console.error("get_isTB", e.name, e.message)
				return resolve("error")
			}
		} else {
			return resolve("done")
		}
	})
}
```

everything debugs - a,b,c,d, no error is trapped. So I need a timeout

These three run a single `Promise.all` -> prototypeLies promise -> kick it all off

Firefox
```
perf detail: global
             isOS [immutables]:    0 ms |    0 ms
         isEngine [immutables]:    0 ms |    1 ms
        [no] isTB [immutables]:    1 ms |    2 ms
```

TB with RFP disabled so I can get some perf
```
perf detail: global
             isOS [immutables]:    1 ms |    1 ms
         isEngine [immutables]:    1 ms |    2 ms
       [yes] isTB [immutables]:   17 ms |   19 ms
```

So I'm happy to add a timeout, but not sure of the syntax to add that. That is e.g. after 100ms set isTB true and resolve as rejected or something - help appreciated

**Comment by abrahamjuliot** [comment]
This timeout should in the try block (before the `css.onload` assignment).
```js 
setTimeout(() => resolve("promise failed"), 100)
// or
setTimeout(() => throw new Error("promise failed"), 100) // handle and catch as an error
```

**Comment by Thorin-Oakenpants** [comment]
Yeah, I can see that on stackoverflow, but I don't know how to fit in it. They were saying to use two functions.

All my promises are this format
```js
function functionName() {
	return new Promise(resolve => {
		// do stuff
		return resolve("whatver")
	})
}
```

**Comment by Thorin-Oakenpants** [comment]
you mean like this? I think I get it now, the resolve can only be resolved once, then the promise is over, including the timeout?

```js
function get_isTB() {
	return new Promise(resolve => {
		if (isFF && isTB === "") {
			try {
				// extensions can cause this to never promise
					// FF is ~1ms, TB is ~20ms
				var timeout = window.setTimeout(function(){
					// assume false: if actually TB, you're a CRAZY edge case
					isTB = false
					console.debug("get_isTB timed out")
					resolve("get_isTB timed out")
				}, 100)
				//setTimeout(() => resolve("promise failed"), 100)

				let t0 = performance.now()
				// etc
```

**Comment by abrahamjuliot** [comment]
Yes, that's it. The timeout resolve only resolves the promise if the promise is still pending.

---
If you like, you can reduce some of the nested bracket layers by checking if `!(isFF && isTB === "")`, resolve early if true, and then the else block can be ommitted, since a `false` condition will execute everything else. It reads fine either way though.
```js
function get_isTB() {
    return new Promise(resolve => {
        // resolve early if condition is true
        if (!(isFF && isTB === "")) {
            return resolve("done")
        }
        // else
        try {

        } catch (e) {

        }
    })
}
```
...And, an arrow function can remove the nested function brackets (minimal nesting).
```js
const get_isTB = () => new Promise(resolve => {
    // resolve early if condition is true
    if (!(isFF && isTB === "")) {
        return resolve("done")
    }
    // else
    try {

    } catch (e) {

    }
})

```

**Comment by Thorin-Oakenpants** [comment]
sweet, timeout working nicely 👍 

alrighty .. tightening up global vars that really need to be correct, and making sure we have them before proceeding

also @sereneblue FYI: PS: interested in how you managed to bypass the triple installtrigger test. Note all this code is not live on TZP yet. The current code has the triple installtrigger test, and a system font test if installtrigger says not firefox: you need to look in the console for something like "isFF caught out: nailed your lying ass" assuming you fail bypassing the system font test

isFF tests
- the value shown is the result of the individual test, not isFF: easier to debug
- I have a global var `skipFF` which skips subsequent isFF tests if isFF is already true
- `math isFF` is actually part of isEngine: it's not actually skipped per se, but it's also not going to make a difference if isFF is already true
- there is a final `status` output: this makes it easy to debug
- tested by simulation of forcing isFF and individual tests to return false
   - as long as one of them has isFF = true, then isFF = true

I added the skipping because saving ~10ms on e.g. system fonts is always good : IDK why both tests have the same perf by the time prototype lies resolves (both tests were run once on a new firefox session) .. `¯\_(ツ)_/¯ ` but it should be faster. e.g. the first three total of 2ms is quicker than 14ms

flow:
- `installtrigger` is set as soon as the generic.js lands
- promise 1: when all js files have reported in then `errors` + `system font` are promised
   - so these are only ever run on a page load/refresh
   - now it's easy to add isFF hardening checks
   - when these are resolved they call the next one
- promise 2: isEngine, isOS, isTB
   - unless there are errors, these also only ever run once
   - isOS and isTB are FF only: hence why isFF checks are promised first
   - once these are resolved then the next one is called
- promise 3: prototype lies
   - once that's resolved then the whole shebang kicks off

more flow
- page load, as above
- global rerun button: starts at promise 2 (we don't need to do all the isFF checks again)
   - the promise 2 checks should basically already be set and instantly resolve
   - promise 3: prototype lies is always reset

❓ @abrahamjuliot So I'm not sure why I need to rerun prototype lies on a global rerun. The extension surely can't change it's lies once the page has loaded? No other site I know of allows global reruns (or section reruns) - which I find is handy as F when testing by flipping prefs or extension settings like iframes in uMatrix. Cover your tracks has a "test again" but it a full test reload AFAICT.

anyway: here's FF with and without the skipping of subsequent isFF tests
![isFFv2](https://user-images.githubusercontent.com/16656956/112068537-057bfe00-8b62-11eb-967d-d4953cee6090.png)

Next up: global navTrueKeys and navFakeKeys - because we use navigator checks all over the place (27 times so far from memory). These would need to be set early on page load, and updated before global-reruns and updated for any individual section re-runs that use it. I haven't timed it, but I think the perf is like 2ms, so maybe I'll just do it for all section reruns

Anyway .,. what do you think? Is it secksie enough?

**Comment by abrahamjuliot** [comment]
Looking good.

An extension's user-setting can change the lie after page load. Running the prototype test on a global or section rerun might be useful to detect if the extension setting reduces or expands the amount of prototype tampering.

**Comment by Thorin-Oakenpants** [comment]
OK, that's cool. Global reruns it's already there. A section rerun has a delay of 160ms, so the user can see items are cleared etc: so that's easy to reduce the delay and rerun prototype lies. A global rerun has a delay of 130ms (I took some time off for prototype)

But I'm confused. I know an extension could change a "lie" : e.g. it could decide to randomly not modify a value. The question really was if the hash of prototype lies could change without a page re-load

---

whats up with that fruit in your code examples .. anyway, here is a png called "banana", and for the luls the next one is "elephant". I've seen these in code on github: I don't think I can use them in Notepad++

This is loading as `file:///`, first time in a new FF session
- generic: the first js file which is generic.js, has landed
   -  not shown obviously but here we warm up mediaDevices and speechSynthesis
- prime unicode: font.js has landed
- run once: all js files have arrived, so we can kick everything off
- start: this is the same as running a global re-run

![banana](https://user-images.githubusercontent.com/16656956/112397164-773a8000-8cf9-11eb-8eee-315b0f7863eb.png)

NI why there is a delay after all the run once stuff, as that's all promisified and kicks it off. It's not my delay, which is 1ms on page loads). Here's a page refresh which shows a bigger diff

![elephant](https://user-images.githubusercontent.com/16656956/112398356-eca75000-8cfb-11eb-962e-5f656be40ed7.png)

**Comment by abrahamjuliot** [comment]
> prototype lie hash 

It's possible to change the prototype lie hash or type of tampering by setting a custom listener that reacts to certain conditions like fingerprinting behavior or too many function calls/property reads from a single context. I think Privacy Possom something [like this](https://github.com/cowlicks/privacypossum/blob/master/src/js/contentscripts/fingercounting.cjs) which is why sometimes the extension appears to not work. It only applies the proxy trap (tampering and deception) if a single script reads a certain level of entropy. If multiple scripts individually fingerprint in small doses, Privacy Possom does not count each script collectively as a single threat, so no tampering is applied. However, something like this would only change the lie hash if TZP triggers the event listener. The listener would function similarly to a click and scroll event that is triggered by user input after the page loads.

> delay
 
I'm not sure about that delay but updating the DOM can cause this.

**Comment by Thorin-Oakenpants** [comment]
OK, I'll rerun prototype for section reruns as well :)

I notice the delay (I use F5) on file:// ... have to close and restart nightly after a dozen or of them. Not noticed it on http .. so will be interesting when I upload all my changes: so much stuff here

I changed up line-height and scrollbar info by only reporting a narrower range of known zoom values: since FF recently added 400 and 500% - that and I think a lot of values on Linux will change with native theming disabled. In order to test it I made it update-able in real time: that was fun.

![big-n-small](https://user-images.githubusercontent.com/16656956/112438448-d6bb7e80-8d3f-11eb-9f89-8c8a3a837697.png)

**Comment by Thorin-Oakenpants** [comment]
OK, so I have `global` (page load, global rerun) vs `section` (which will include click-here if applicable: e.g. the manual audio test)
- The global fingerprint data and details, prototype lies and details, and known lies are all a snapshot: they do not change unless you do a global-rerun (or refresh the page! doh)

On all runs (page-load, global-rerun, section reruns)
- section data and section detail is updated
- so are a couple of "global" vars used everywhere: protoLies, and navKeys

e.g.
```js
let jsFiles = [],
	// global snapshot
	gLies = [],
	gLiesDetail = {},
	gLiesKnown = [], // we only ever add if gRun
	gCheck = [],
	gCount = 0,
	gData = [], // e.g. 117 metrics
	gDetail = {}, // e.g. the list of css colors
	gPerf = [],
	gPerfDetail = [],

	// section
	sData = {}, // the section metrics: e.g. 6 metrics in css
	sDetail = {}, // e.g. the list of css colors
	sPerfDetail = [],

	// current: reset on global/re-runs (and click-here if required)
	// used everywhere, always promised first
	protoLies = [], // e.g. protoLies.includes("Navigator.hardwareConcurrency")
	navKeys = {} // trueKeys, falseKeys

```

Now one thing about Canvas Blocker is that it functions with `file:///`. So I tried to see if I could get a difference in `gLies` (global snapshot) and `protoLies` (updated before each section rerun) .. by toggling various CB APIs on and off

e.g
- I would start with CB protecting canvas, domrect, screen, navigator, textmetrics: and get a `gLies` hash snapshot
- then in CB settings I would disable domrect, screen, navigator, textmetrics, and rerun any sections and output the `protoLies` hash to console
- the hash never changes

Now, IANAExpert on extensions, but I'll take your word for it that the hashes can change without a page reload/refresh?

Right?

**Comment by abrahamjuliot** [comment]
Correct. Here's an example of Privacy Possom starting with `none` on page load and then `10 lies` on re-run.

![possom2](https://user-images.githubusercontent.com/6946045/112763534-af6fe600-8fb9-11eb-9cbe-1882ee3d6a6a.gif)

**Comment by Thorin-Oakenpants** [comment]
Cool, you're awake.

I am fixing up the canvas timings, by starting and ending the perf inside each function
the `[k]` (known value) tests uses sha1 and are not an issue
the run `[1]` and `[2]` tests though return `undefined` (not a string) (except toBlob bvcause IDK, it takes longer: not what I was after)

![perf](https://user-images.githubusercontent.com/16656956/112765851-aead7300-8ffe-11eb-9cd0-94f02bdceb8f.png)

old example
```js
	{
		name: "toDataURL",
		value: function(){
			let t1 = performance.now()
			let data = hashDataURL(getFilledContext().canvas.toDataURL())
			log_perf("toDataURL ["+ runNo +"] [canvas]",t1,gt0,data)
			return data
		}
	},
```

new example
```js
	{
		name: "toDataURL",
		value: function(){
			let t1 = performance.now()
			Promise.all([
				hashDataURL(getFilledContext().canvas.toDataURL())
			]).then(function(data){
				log_perf("toDataURL ["+ runNo +"] [canvas]",t1,gt0,data) // DATA is good
				return data // DATA is undefined
			})
		}
	},
```

hashDataURL
```js
	function hashDataURL(url){
		return crypto.subtle.digest("SHA-256", new TextEncoder("utf-8").encode(url)).then(hashToString)
	}
```

Is this even right? I mean the `k` values using sha1 finish super early, but all the rest seem to finish at the same time as the cyprto function de-bottlenecks or something. Don't get me wrong, the perf start times are more accurate being per item (previously they just all used the same start time)

Here's without the promises: and obviously 2ms is a lie
![perf2](https://user-images.githubusercontent.com/16656956/112766184-1e702d80-9000-11eb-8035-fe95ed041852.png)

I did play around with changing everything to sha1, since that doesn't need any promises, but overall it doesn't speed anything up, and the longer sha-256 is better for handling my noise/random notations etc

I'm sure I just need a slight tweak to how I "promise" the "data"

**Comment by Thorin-Oakenpants** [comment]
> Here's an example of Privacy Possom...

OK, cool. My local copy is all good for rebuilding prototype lies for use in section reruns

I could never get Privacy Possum to do anything (on FF). From memory it needs to learn or something, and then the extension is about 3 years old? ahh OK, says Jul 2019 on AMO, but https://github.com/cowlicks/privacypossum is like 3 years

https://addons.mozilla.org/en-US/firefox/addon/privacy-possum/versions/
- Sep 1, 2018 was the last FP protection changes

Yeah, I could never get this to extension to work. Maybe I should try it again. Maybe it was the "rerun" and I never did that. ☕

**Comment by Thorin-Oakenpants** [comment]
actually, sha1 takes about twice as long

<details><summary>stroke me gently to make me grow</summary><p>

SHA1
```
perf detail: re-runs
        toDataURL [1] [canvas]:   12 ms |   15 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
     getImageData [1] [canvas]:   54 ms |   73 ms | a5cc0da83ce68ea816b51596bf56d3e68c983296
    isPointInPath [1] [canvas]:    1 ms |   74 ms | 1c1952cf7f263b0e80c1a9e92bae1143f8588d13
  isPointInStroke [1] [canvas]:    9 ms |   83 ms | 895afb042cd7b5b19dc8f9fd9d3243d28ab86fb0
        toDataURL [2] [canvas]:    6 ms |   89 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
     getImageData [2] [canvas]:   34 ms |  125 ms | a5cc0da83ce68ea816b51596bf56d3e68c983296
    isPointInPath [2] [canvas]:    1 ms |  127 ms | 1c1952cf7f263b0e80c1a9e92bae1143f8588d13
  isPointInStroke [2] [canvas]:    8 ms |  135 ms | 895afb042cd7b5b19dc8f9fd9d3243d28ab86fb0
        toDataURL [k] [canvas]:    2 ms |  138 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
     getImageData [k] [canvas]:   35 ms |  174 ms | 67a2c3bc2f7ccf8c92d57b94586784f19d98a2f0
    isPointInPath [k] [canvas]:    0 ms |  174 ms | f44c70171a197cc26df382603e76f4ba581e2d8f
  isPointInStroke [k] [canvas]:    1 ms |  175 ms | 1b636fb26edee73d7ca832edd1112e0021566a50
           toBlob [1] [canvas]:  163 ms |  178 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
           toBlob [2] [canvas]:   92 ms |  181 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
           toBlob [k] [canvas]:   43 ms |  181 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
           --------------------
        toDataURL [1] [canvas]:    9 ms |   10 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
     getImageData [1] [canvas]:   38 ms |   51 ms | a5cc0da83ce68ea816b51596bf56d3e68c983296
    isPointInPath [1] [canvas]:    1 ms |   53 ms | 1c1952cf7f263b0e80c1a9e92bae1143f8588d13
  isPointInStroke [1] [canvas]:    8 ms |   61 ms | 895afb042cd7b5b19dc8f9fd9d3243d28ab86fb0
        toDataURL [2] [canvas]:    5 ms |   67 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
     getImageData [2] [canvas]:   35 ms |  104 ms | a5cc0da83ce68ea816b51596bf56d3e68c983296
    isPointInPath [2] [canvas]:    2 ms |  106 ms | 1c1952cf7f263b0e80c1a9e92bae1143f8588d13
  isPointInStroke [2] [canvas]:    7 ms |  113 ms | 895afb042cd7b5b19dc8f9fd9d3243d28ab86fb0
        toDataURL [k] [canvas]:    2 ms |  116 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
     getImageData [k] [canvas]:   31 ms |  149 ms | 67a2c3bc2f7ccf8c92d57b94586784f19d98a2f0
    isPointInPath [k] [canvas]:    1 ms |  150 ms | f44c70171a197cc26df382603e76f4ba581e2d8f
  isPointInStroke [k] [canvas]:    1 ms |  151 ms | 1b636fb26edee73d7ca832edd1112e0021566a50
           toBlob [1] [canvas]:  145 ms |  155 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
           toBlob [2] [canvas]:   89 ms |  157 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
           toBlob [k] [canvas]:   42 ms |  158 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
           --------------------
        toDataURL [1] [canvas]:    6 ms |    8 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
     getImageData [1] [canvas]:   39 ms |   50 ms | a5cc0da83ce68ea816b51596bf56d3e68c983296
    isPointInPath [1] [canvas]:    1 ms |   51 ms | 1c1952cf7f263b0e80c1a9e92bae1143f8588d13
  isPointInStroke [1] [canvas]:    8 ms |   59 ms | 895afb042cd7b5b19dc8f9fd9d3243d28ab86fb0
        toDataURL [2] [canvas]:    5 ms |   64 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
     getImageData [2] [canvas]:   33 ms |  100 ms | a5cc0da83ce68ea816b51596bf56d3e68c983296
    isPointInPath [2] [canvas]:    1 ms |  102 ms | 1c1952cf7f263b0e80c1a9e92bae1143f8588d13
  isPointInStroke [2] [canvas]:    7 ms |  109 ms | 895afb042cd7b5b19dc8f9fd9d3243d28ab86fb0
        toDataURL [k] [canvas]:    2 ms |  112 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
     getImageData [k] [canvas]:   34 ms |  147 ms | 67a2c3bc2f7ccf8c92d57b94586784f19d98a2f0
    isPointInPath [k] [canvas]:    0 ms |  147 ms | f44c70171a197cc26df382603e76f4ba581e2d8f
  isPointInStroke [k] [canvas]:    1 ms |  148 ms | 1b636fb26edee73d7ca832edd1112e0021566a50
           toBlob [1] [canvas]:  143 ms |  151 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
           toBlob [2] [canvas]:   89 ms |  153 ms | 8da88c6d0f6cabb44e906e31e8eba590cb1d7349
           toBlob [k] [canvas]:   42 ms |  154 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
```

SHA256
```
perf detail: re-runs
        toDataURL [1] [canvas]:    4 ms |    5 ms | [object Promise]
     getImageData [1] [canvas]:    1 ms |    8 ms | [object Promise]
    isPointInPath [1] [canvas]:    1 ms |    9 ms | [object Promise]
  isPointInStroke [1] [canvas]:    8 ms |   17 ms | [object Promise]
        toDataURL [2] [canvas]:    3 ms |   20 ms | [object Promise]
     getImageData [2] [canvas]:    1 ms |   23 ms | [object Promise]
    isPointInPath [2] [canvas]:    1 ms |   24 ms | [object Promise]
  isPointInStroke [2] [canvas]:    8 ms |   32 ms | [object Promise]
        toDataURL [k] [canvas]:    3 ms |   35 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
     getImageData [k] [canvas]:   30 ms |   66 ms | 67a2c3bc2f7ccf8c92d57b94586784f19d98a2f0
    isPointInPath [k] [canvas]:    1 ms |   67 ms | f44c70171a197cc26df382603e76f4ba581e2d8f
  isPointInStroke [k] [canvas]:    1 ms |   68 ms | 1b636fb26edee73d7ca832edd1112e0021566a50
           toBlob [1] [canvas]:   65 ms |   70 ms | [object Promise]
           toBlob [2] [canvas]:   50 ms |   70 ms | [object Promise]
           toBlob [k] [canvas]:   36 ms |   71 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
           --------------------
        toDataURL [1] [canvas]:    3 ms |    4 ms | [object Promise]
     getImageData [1] [canvas]:    2 ms |    8 ms | [object Promise]
    isPointInPath [1] [canvas]:    1 ms |    9 ms | [object Promise]
  isPointInStroke [1] [canvas]:    7 ms |   16 ms | [object Promise]
        toDataURL [2] [canvas]:    3 ms |   19 ms | [object Promise]
     getImageData [2] [canvas]:    1 ms |   22 ms | [object Promise]
    isPointInPath [2] [canvas]:    1 ms |   23 ms | [object Promise]
  isPointInStroke [2] [canvas]:    7 ms |   30 ms | [object Promise]
        toDataURL [k] [canvas]:    2 ms |   33 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
     getImageData [k] [canvas]:   29 ms |   63 ms | 67a2c3bc2f7ccf8c92d57b94586784f19d98a2f0
    isPointInPath [k] [canvas]:    3 ms |   66 ms | f44c70171a197cc26df382603e76f4ba581e2d8f
  isPointInStroke [k] [canvas]:    0 ms |   66 ms | 1b636fb26edee73d7ca832edd1112e0021566a50
           toBlob [1] [canvas]:   64 ms |   68 ms | [object Promise]
           toBlob [2] [canvas]:   49 ms |   68 ms | [object Promise]
           toBlob [k] [canvas]:   36 ms |   69 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
           --------------------
        toDataURL [1] [canvas]:    4 ms |    6 ms | [object Promise]
     getImageData [1] [canvas]:    0 ms |    9 ms | [object Promise]
    isPointInPath [1] [canvas]:    1 ms |   11 ms | [object Promise]
  isPointInStroke [1] [canvas]:    7 ms |   18 ms | [object Promise]
        toDataURL [2] [canvas]:    3 ms |   21 ms | [object Promise]
     getImageData [2] [canvas]:    2 ms |   25 ms | [object Promise]
    isPointInPath [2] [canvas]:    0 ms |   25 ms | [object Promise]
  isPointInStroke [2] [canvas]:    8 ms |   33 ms | [object Promise]
        toDataURL [k] [canvas]:    3 ms |   36 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
     getImageData [k] [canvas]:   29 ms |   66 ms | 67a2c3bc2f7ccf8c92d57b94586784f19d98a2f0
    isPointInPath [k] [canvas]:    1 ms |   67 ms | f44c70171a197cc26df382603e76f4ba581e2d8f
  isPointInStroke [k] [canvas]:    1 ms |   68 ms | 1b636fb26edee73d7ca832edd1112e0021566a50
           toBlob [1] [canvas]:   64 ms |   70 ms | [object Promise]
           toBlob [2] [canvas]:   49 ms |   70 ms | [object Promise]
           toBlob [k] [canvas]:   34 ms |   70 ms | 8c70ed9a7dbe6d72e3d1a4e448522012661cfbed
```

</p></details>

**Comment by abrahamjuliot** [comment]
Since `crypto.subtle.digest` is a promise and in `hashDataURL` we want to return the result of `hashToString`, we need to await the promise before returning it.

```js
// make hashDataURL async
async function hashDataURL(url){
  // await the result of hashToString
  return await crypto.subtle.digest("SHA-256", new TextEncoder("utf-8").encode(url)).then(hashToString)
}
```

Every function that runs `hashDataURL` should be `async` as well and `await` the result
```js
async function getValue(){
  let data = await hashDataURL(reader.result)
  return data
}
```
And, every function that runs the function that runs `hashDataURL` should also be `async` and `await` the result

```js
async function output(){
  let value = await getValue()
  return value
}
```

As you may see, this can create a lot of nested `async` and `await` and the parent global function has to be an async function (or return a new `Promise`) as well.

A possible solution: instead of hashing data in the `value` function, hash it in the parent promise, but make sure it is an `async` function.

```js
var finished = Promise.all(outputs.map(function(output){
   return new Promise(async function(resolve, reject){
      let data = output.value()
      //... then determine if the data should be hashed
      
      // if it should be hashed
      let hash = await crypto.subtle.digest("SHA-256", new TextEncoder("utf-8").encode(url)).then(hashToString)
      resolve(hash)
   })
}))
```

You could also write the above like this

```js
```js
var finished = Promise.all(outputs.map(function(output){
   /// async functions are promises
   return async function(){
      // handle errors using try/catch blocks
      let data = output.value()
      //... then determine if it should be hashed
      
      // if it should be hashed
      let hash = await crypto.subtle.digest("SHA-256", new TextEncoder("utf-8").encode(url)).then(hashToString)
      
      // the return is the resolve in an async function
      return hash
   })() // immedietly invoke with ()
}))
```

**Comment by Thorin-Oakenpants** [comment]
^^ yikes. not sure if this is worth it now. I was trying to measure more accurately for #36 . I can reduce the precision in RFP using prefs (I think I can get to 1ms: maybe 10ms is the lowest). It's probably not worth all the nesting and asyncing and waiting: I could temporarily just output to console each time I need a time, and show timestamps in the console to work it out. It's just so I can confirm the canvas is a perf issue: I'm not convinced it is - the other day I removed woff font from the promise.all in fonts, and everything now seems peachy.

---

@sereneblue has been sneaky :)  Hey serene, how did you bypass my triple installtrigger check (chameleon was posing as chrome on macOS)

PS: you have passed level one, proceed to level two (error codes). When you have mastered all levels (currently four), you get to fight the boss.
![isFF](https://user-images.githubusercontent.com/16656956/112793242-73d62a00-9054-11eb-8901-09c990bc8192.png)

**Comment by sereneblue** [comment]
@Thorin-Oakenpants The recent update added some code to get around some additional fingerprinting methods. InstallTrigger is removed when a non-Firefox profile is used and several browser APIs are implemented/stubbed. This _should_ get around checks for `window.safari` or `window.chrome`. I don't think I'll work on bypassing your error codes check. That's a pretty deep rabbit hole.

**Comment by Thorin-Oakenpants** [comment]
@sereneblue Thanks, I know. I was more interested in the `how` ... as Cydec tries to do this as well, but I guess my code snippet helped you

```
  if (data.browser !== "firefox") {
    delete window.InstallTrigger;
    delete window.InstallTriggerImpl;
  }
```

**Comment by Thorin-Oakenpants** [comment]
closing: have sorted out timing out in promises, and overall hardened all the `isThings` used throughout my code: promising them once on each pageload

@sereneblue FYI: on Cydec
- cydec also tries to mess with error strings (which is not a real solution IMO, since what errors are generated and how they are, can be different depending on the script: i.e it's a game of whack a mole). The error's generated in my test are from passing a string to a new function (thanks to abraham)
```js
const newFn = x => typeof x != 'string' ? x : new Function(x)()

//and here are the three error strings used to check if you are firefox
try {newFn("alert('A)")} catch(e) {res.push(e.name +": "+ e.message)}
try {newFn(`null.value = 1`)} catch(e) {res.push(e.name +": "+ e.message)}
try {let test = newFn("let a = 1_00_;")} catch(e) {res.push(e.name +": "+ e.message)}
```

* cydec also mangles math function results: which is the fourth isFF test (the one which also sets the isEngine)

That cydec really is a piece of work: right now I'm returning `[object Object]` in navigator.connection because of it's hijinks
