### ISSUE TITLE
detect Brave Shields

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#57]
https://github.com/arkenfox/TZP/blob/095854ed5678ecedf2d2c3bca0d02b021f8cb49a/js/generic.js#L123-L127

One of the functions that runs on page load, global reruns and section reruns .. promised before we do any FPing ...  is `get_navKeys()` which I use everywhere, same with isRFP, isFF, isOS etc. As you can see, during this function I also set isBrave. What I would like to do is also set isBraveShield (I know changing the shield triggers a page reload: but I don't mind rechecking before every manual clicking of run buttons: since it fits in there)

Now I currently set isBraveShield just the once, when doing the plugin test - which is not the right place, but clearly a good test for it. Is there an elegant, fast way to detect if Brave Shields is on - and indeed, even if it is standard or strict. I guess the answer is going to be .. via the plugin test .. right?

Edit: sorry for the confusion .. my local copy uses `isBraveShield` instead of `isBraveFP` - it doesn't have to be a boolean

**Comment by abrahamjuliot** [comment]
This will get the mode.

```js
function getBraveMode() {
    try {
        // strict mode returns null supported extensions
        const canvas = document.createElement('canvas')
        const gl = canvas.getContext('webgl')
        if (!gl.getSupportedExtensions()) {
            return 'strict'
        }
        // standard and strict mode do not have chrome plugins
        const chromePlugins = /Chrome PDF (Plugin|Viewer)/ 
        const pluginsList = [...navigator.plugins]
        const hasChromePlugins = pluginsList
            .filter(plugin => chromePlugins.test(plugin.name)).length == 2
        if (!hasChromePlugins) {
            return 'standard'
        }
        return 'allow'
    } catch (e) {
        return 'unknown'
    }
}
// if 'brave' in navigator...
getBraveMode()
```
Some older versions of Brave might have the `#pdf-plugin-name` flag which provides the `Chromium` and `Microsoft Edge` option, so you could change the regex line to `const chromePlugins = /(Chrom(e|ium)|Microsoft Edge) PDF (Plugin|Viewer)/ `.

On the [farbling test page](https://dev-pages.bravesoftware.com/farbling.html), `diff` items in the `Strict vs. Standard` column can potentially reveal strict mode.

**Comment by Thorin-Oakenpants** [comment]
Cool. I hadn't looked yet at what else could be checked. I think we can ignore older versions of Brave since they auto-update. It's also counterproductive to run extensions in Brave that would interfere in these metrics (but it doesn't mean it doesn't happen). 

Probably could do with some extra checks to be more robust - it's just that Brave doesn't have anywhere near the metrics being protected that RFP covers - not that I think testing for a set of RFP measures is robust: these same results can be mimicked in Firefox without RFP, or indeed fail miserably [1]

[1] `https://github.com/EFForg/cover-your-tracks/issues/50#issuecomment-754417608`
- not all TB's inner windows are multiples of 100 (lots of bugs such as toolbar issues, changing chrome elements, tiling managers, devicePixelRatio+system-zoom issues, manual resizing issues, and letterboxing can be flipped independently.. to name but a few)
- timezone can be overriden by an extension

**Comment by Thorin-Oakenpants** [comment]
done - https://github.com/arkenfox/TZP/commit/f37b3c86d1c62b88085758ad7a63356a398779b5
