### ISSUE TITLE
promisify domrect

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#8]
canvas does two "passes" and a third one where it hashes a known result - here's the logic
```js
if (pass1 == pass 2) {
  if (pass3 = false) {
   result = "noise detected" // stealth/cached randomizing
  } else {
    result = "real value"
  }
} else {
 result = "randomizing on each pass"
}
```

pretty straight forward. Now I've done the same to domrect. That is two passes and the third is the shift by 0.25 pixels and a comparison to detect noise. What I would like is to turn the three passes or runs into promises

https://github.com/arkenfox/TZP/blob/276833f33d6a8f961ddf69e2ac0981306f7b5326/js/domrect.js#L111-L120

How do I turn those three runs into a promise.all - run() doesn't actually return anything? @abrahamjuliot

**Comment by abrahamjuliot** [comment]
Void functions can resolve undefined. 

```js
function run(runtype, runarray) {
  return new Promise(function(resolve, reject) {
    // execute procedure...

    // if success
    resolve()
  })
}

Promise.all([
  run(0, run0),
  run(1, run1),
  run(2, run2)
]).catch(error => {
  console.error(error.message)
})
```

The `move div` step can be handled in the promise when `runtype` matches 2

**Comment by Thorin-Oakenpants** [comment]
> The `move div` step can be handled in the promise when runtype matches 2

Yeah. I moved that into the run() function yesterday (locally). I also have to reset it if runtype = 0 (because I have a rerun button)

> script

The arrays are still empty, same issue I had yesterday when I tried the above similar code. The `run()` function runs a set of four tests - it calls `createTest("tests 1 to 4")` and here is were I also capture an error (e.g. if CB blocks something like `getClientRects`). So calling the four tests will resolve quickly, but the results haven't been recorded yet

also not sure how to attach the catch there
```js
	Promise.all([
		run(0, run0),
		run(1, run1),
		run(2, run2)
	]).then(function(){
		console.debug("domrect perf", (performance.now()-t0) + "ms")
		// debugging
		run0.sort()
		run1.sort()
		console.log("run0\n - " + run0.join("\n - "))
		console.log("run1\n - " + run1.join("\n - "))
	})
	//]).catch(error => {
	//	console.error(error.message)
	//})
```

here's the console. The second output is after I use a timer of `1ms` before I start, as seen below. It just seems that a setTimeout is enough to cause the code to wait for previous shit to finish. Anyway, we want promises
https://github.com/arkenfox/TZP/blob/127c2cb3ee2d4d81cc38f384292fee6833c6fd16/js/domrect.js#L144

So below are the results from when I load TZP, and then when I "re-rerun" the section. Note the perf

![perf](https://user-images.githubusercontent.com/16656956/93657300-4e22f500-fa21-11ea-9377-38b550d22540.png)

So I don't quite know how to turn `createTest` into a promise (isn't it already with callback?) that reports back to `run()` which is a promise that reports back to `promise.all` - so that promise.all doesn't do jack shit until everything is ready

**Comment by abrahamjuliot** [comment]
I'm not sure if this fixes the issue, but everything in the `setTimeout` callback function should be placed in the promise `then` callback. You can optionally return `resolve(runarray)` at the end of the promise and `promise.all` should `then` destructure the 3 runs -- this might help debug the array if it returns empty.

```js
function run(runtype) {
  let runarray = []
  return new Promise(function(resolve, reject) {
    // execute procedure...

    // if success
    return resolve(runarray)
  })
}

Promise.all([
  run(0),
  run(1),
  run(2)
]).then(function([run0, run1, run2]) {
  // do something with run0, run1, and run2
  // the setTimeout callback should execute here (no setTimout needed)
}).catch(error => {
  // if a run fails
  console.error(error.message)
})
```

> createTest

In a similar fashion, you could create a nested `promise.all` that awaits a promise of the `try/catch` block and `createTest`, but the performance gain might be minimal. The resolve of the parent promise should be returned in the nested `then`. It could look something like this:

```js
function run(runtype) {
  let runarray = []
  return new Promise(function(resolve, reject) {
    Promise.all([
      do1(runarray),
      do2(runarray),
      do3(runarray),
      do4(runarray)
    ]).then(function() {
      return resolve(runarray)
    }).catch(error => {
      // if a run fails
      return reject(error)
    })
  })
}
```

**Comment by Thorin-Oakenpants** [comment]
I've refactored it a bit
- removed multiple run arrays
- moved the error handling out of `run()` into `createTest()`
- temp output of hashes/errors in `createTest()` - but will be ultimately be done in a new function (see next point)
- separate function to analyze and output display data: provide domrect overall hash and add random/noise notations etc

so in a nutshell
```js
"use strict";

function outputDomRect() {

	// analyze and output
	function analyze() {
		// output hashes/randomness/noise/perf
	}

	function getElements(){
		return Array.from(document.querySelectorAll(".testRect"))
	}
	function createTest(method, runtype, callback){
		function performTest(runtype){
			try {
				// store hashes in results eg: 0:dr1:hash
			} catch(e) {
				// store error in results eg: 0:dr2:e.name
			}
		}
		performTest(runtype)
	}

	// run
	function run(runtype) {
		return new Promise(function(resolve, reject) {
			// move  or reset div
			createTest("dr1", runtype, blah)
			createTest("dr2", runtype, blah)
			createTest("dr3", runtype, blah)
			createTest("dr4", runtype, blah)
			resolve()
		})
	}

	let results = []
	Promise.all([
		run(0),
		run(1),
		run(2)
	]).then(function(){
		// if this worked then we would call analyze()
	})

	setTimeout(function(){
		// this works but I prefer a promise
		analyze()
	}, 100)

}

outputDomRect()

```

**Comment by Thorin-Oakenpants** [comment]
Sorry, I posted my refactoring post before I saw your answer. None of that is going to work (I think)

What's causing the delay is the sha256 calculation

if I replace
https://github.com/arkenfox/TZP/blob/55e079cd9fcb0d0164d539f65f924553d53e6d18/js/domrect.js#L69-L75
with
```js
				results.push(runtype+":"+method+":"+data)
```
then it works. I can even use a sha1 function.

So how do we counter that?

**Comment by abrahamjuliot** [comment]
You could let the sha256 calculation remain and await the hash response. Since the function is nested, the parent functions `outputDomRect`, `createTest`, and `performTest` should be `async` and `performTest` and  `createTest` should `await` their execution. Another option is to store the data ArrayBuffer in an object (alongside runtype and method) in the results array (`results.push({ runtype, method, data })`) and then process each result in the promise.all `then` response.

store data ArrayBuffer option

```js
Promise.all([
  run(0),
  run(1),
  run(2)
]).then(function() {
  //...
  results.forEach(result => {
    let { runtype, method, data } = result
    crypto.subtle.digest("SHA-256", data).then(function(hash) {
      let tmp = byteArrayToHex(hash)
      //...
    })
  })
})
```

aync/await option

```js
async function outputDomRect() {

  //...
  async function createTest(method, runtype, callback) {
    //...
    async function performTest(runtype) {
      try {
        //...
        // await hash
        let hash = await crypto.subtle.digest("SHA-256", data)
        // store hash...
      } catch (e) {
        //...
      }
    }
    // await test
    await performTest(runtype)
  }

  // run
  async function run(runtype) {
    return new Promise(async function(resolve, reject) {
      //...
      // await each test
      await createTest("dr1", runtype, function(element) {
        return element.getClientRects()[0]
      })
      await createTest("dr2", runtype, function(element) {
        return element.getBoundingClientRect()
      })
      await createTest("dr3", runtype, function(element) {
        let range = document.createRange()
        range.selectNode(element)
        return range.getClientRects()[0]
      })
      await createTest("dr4", runtype, function(element) {
        let range = document.createRange()
        range.selectNode(element)
        return range.getBoundingClientRect()
      })
      resolve()
    })
  }

  //..

  Promise.all([
    run(0),
    run(1),
    run(2)
  ]).then(function() {
    //...
  })

  //...
}
```

**Comment by Thorin-Oakenpants** [comment]
Thanks

I can try those. I already thought I could just pass the data and hash everything in analyse() but it's cleaner to do it within each performTest... it's 8 hash results (2 runs x 4 tests: I can exclude hashing on run 3), and then another one would be needed later for a (sub)section hash. Meanwhile canvas and audio also use sha256 .. which (and IANAE) causes some bottlenecking ?

Since I also plan to add an svg subsection, I think using sha1 is easier and cleaner. It's also a lot faster (and I'm not worried about sha1 being deprecated in crypto, since I've rolled my own) - and IMO it's just fine for FPing (collisions and all that)

**Comment by Thorin-Oakenpants** [comment]
done https://github.com/arkenfox/TZP/pull/10 (and a couple of tweaks afterwards)
