### ISSUE TITLE
fuck I hate blink at times :) .. reminder for domrect

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#82]
I find using android to be a PITA, and especially hard to debug anything, and I find dealing with blink to also be a PITA

My phone is android 10
- so I allowed chrome to be enabled on my phone via apps. It was on v85, and I checked the webaudio. It was same as android 11 according to FPJS.
- I then checked my phone version and it forced an update check, and updated the kernel etc from August 2020. And after that I updated chrome (to v90), and checked webaudio again ... now it's the same as windows
- so IDK if that was a chrome change or a kernel change (or something related to the android update)
- so that's interesting

```
// blink: CPU touches FP?
	// ToDo: get the full hash for an array of knownGood
	// https://fingerprintjs.com/blog/audio-fingerprinting/
	// windows + android10: 124.04347527516074  <-- my android 10 result after system+chrome update
	// chromeOS: 124.04347721464
	// macOS 11: 124.0434806260746
	// android 9: 124.08074500028306
	// android 10+11: 124.08075528279005  <-- my android 10 result before system+chrome update
```

---

Anyway, I also notice that for chrome 85 (and 90) the known hash for toDataURL and toBlob had changed
- NFI when that happened, or why, did they change the way they compress the PNG data? desktop didn't change
- so now I allow two known hashes for blink for those
- so that's interesting

---

And now I also notice that domrect on chrome now throws me a TZP alert for that domrect has multiple hashes (and no lies), when TF did this start happening (or maybe it's always been like this: I just simply never really test anything android except FF)

here's TZP
![exhibitA](https://user-images.githubusercontent.com/16656956/120723626-9f94e680-c4c1-11eb-9d9e-6fcfaf031b8b.png)

and I thought, well golly gosh (actually I used the F word), my code must be flawed, so let me see what happens on CB's test

here's CB (snipped and bits moved to make the image smaller)
![exhibitB](https://user-images.githubusercontent.com/16656956/120723708-cb17d100-c4c1-11eb-8a15-3424154b1b63.png)

phew, so it's NOT me (queue sighs of relief)

Now I just changed the domrect section to return a single value, so this screws all of that up, and I return "unknown"

@abrahamjuliot has blink on android just recently returned a different value for `Element.getBoundingClientRect`, or has it always been like that? As I said, I find it hard to debug .. what is elements are being changed here? hang on a sec, CB tests have a `+` data button

brb

**Comment by abrahamjuliot** [comment]
It's been like that for some time. Here's Chrome 84 on Chrome OS and Chrome 86 on Android 9 (same machine).
![image](https://user-images.githubusercontent.com/6946045/120731756-18337d00-c499-11eb-8706-81fa34291d3d.png).

Getting these to match may only require adjusting the element size, perspective, or position. On the creep dev site, I'm now comparing range methods to element methods and they match on Chrome 84 and 86. I set the width and height of each element to 1000% and only use an iframe, but in some versions, there is still some mismatching. I just show the diffs and let it pass. Most of the lies are caught with math and shift tests.

![image](https://user-images.githubusercontent.com/6946045/120732882-e91e0b00-c49a-11eb-8e17-7bcc6960b9ee.png)
![image](https://user-images.githubusercontent.com/6946045/120733119-5f227200-c49b-11eb-9807-ded05409aabb.png)

**Comment by Thorin-Oakenpants** [comment]
This isn't about detecting a lie (and shift method doesn't catch chameleon which is why I came up with the known rect). This is about getting a stable result across the four metrics, because it makes it so much easier

I think I just need to reduce what is checked in blink, to eliminate the items that GeTtRiGgERrEd with a different value. Which is what you're doing

That would make it easy for bypasses. But do I really care? I'd rather grab entropy and if someone lies and I can't bypass, so what? So I'm torn .. I think I just want to allow multiple values for blink

so my entropy trumps your entropy ... nah nah nah nah 😛 

---

I'm reworking domrect anyway, so I can color up bypasses, lies: record them as a single lie and bypass, and I'm also recording blocks and randomizing methods (i.e two pass, randomizing same amount, randomizing variable amounts) 

Before I was outputting as I analyzed .. now I'm outputting only after I have all the info. So here I can use logic to allow blink to have multiple values, as long as I do not see a lie: and I can return multiple values for blink

and damnit ... `Range` is different in your pics ... mine was `Element`  so seems like `getBoundingClientRect` can vary which makes things messy for "bypassing"

**Comment by Thorin-Oakenpants** [comment]
whats the TZP web audio on chromeOS and android 9: does it match what FPJS said?

**Comment by Thorin-Oakenpants** [comment]
lols: number of speech engines: android 10: chrome says 53 (I see your pic shows 52) Firefox says 62 ... `¯\_(ツ)_/¯`

**Comment by Thorin-Oakenpants** [comment]
I like how CB still spoofs with `file://` scheme - makes it easy for me to test

CB faking all
![exhibitD](https://user-images.githubusercontent.com/16656956/120737008-d4fafd80-c4dc-11eb-824e-c2ff64f41760.png)

the marginCompare will get refined once I can test chameleon live etc. But what the above is saying (CB fake all four) is 33 measurements !== the shift value of 0.25 ... and of those 18 differed by various amounts. If I remember rightly, chameleon has some cases where his random static spoof shifting value like `0.000000005` could sometimes be calculated at `0.0000000049` or something.

So I'll refine that based on some chameleon tests, to show static or random

That gives me
- blink vs FF knowledge
- values to display
- logic to know if it's each is a lie (and if I can bypass on FF) = color shit up
- lie knowledge for methods: such as two pass and/or how the lie is created (a random variance or a static one)

CB blocking `getClientRects`

![exhibitE](https://user-images.githubusercontent.com/16656956/120738229-05dc3200-c4df-11eb-98c5-103d2393605c.png)

The compares are always four (or more if we add more methods), and anything false in the first three is a detected lie: i.e an error or block doesn't register as a lie

I think I got this, and can handle the blink curve balls: don't care about bypasses in blink TBH

**Comment by Thorin-Oakenpants** [comment]
> 124.04344884395687 on Chrome OS 84 (distinct from FPJS on Chrome OS 89)

I assume TZP said you were lying, because your chrome OS 84 was less than the blinkmin - see commit above

> We might also find some unique Chrome OS results in Chrome OS CloudReady VMWare.

Yeah, definitely something going on there with with android. I mean mine changed on me after a system update (and chrome update just to confuse WTF is going on)

I really wish we could push experiments on a set of people, been wanting that for over almost three years

**Comment by Thorin-Oakenpants** [comment]
chrome desktop: and what I thought was the same for blink everywhere
![chrome](https://user-images.githubusercontent.com/16656956/120911601-2b507380-c678-11eb-8e3b-f492eb37a3c2.png)

chrome android
![chrome-android](https://user-images.githubusercontent.com/16656956/120911605-33101800-c678-11eb-80b1-ae39d9b56189.png)

firefox for comparison
![ff](https://user-images.githubusercontent.com/16656956/120911631-55a23100-c678-11eb-984b-60dc88188d94.png)

I wonder if this is something that can be followed up on in image decoding, see #79 - not that we need any help to detect engines, but it may have some entropy elsewhere, IDK .. why is the PNG different? hardware specs, android update, loki?

**Comment by Thorin-Oakenpants** [comment]
ok this is done: we always return four in the results, and we don't use non-lies to bypass lies in non-FF
