### ISSUE TITLE
window.clientinformation

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#93]
- FF91+ `dom.window.clientinformation.enabled` [1717072](https://bugzilla.mozilla.org/show_bug.cgi?id=1717072)
- `https://github.com/whatwg/html/pull/6721`

@abrahamjuliot

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot so this is just an alias, and doesn't add anything (besides feature detection), right? i.e it doesn't affect extensions? i.e internally it just maps to navigator, and extensions still spoof?

**Comment by abrahamjuliot** [comment]
That's correct. `navigator` and `clientInformation` both return `Navigator`. For example, this lite spoof on device memory will affect both.

```js
Object.defineProperty(navigator, 'deviceMemory', {value: -100})
```

**Comment by Thorin-Oakenpants** [comment]
Cool, closing then. I don't need the feature detection
